' TestFlashAPI.vb : Declares the DLL functions for vb7.
' Generated by C:\work_bluesuite_2_5\p4\common\hosttools\bluesuite_2_5\prodtest\scripts\extract_tt_api.pl from TestFlash.h; TestPS.h;  at 03/02/14 - 11:39:57

Imports System.Text

Module TestFlash
Declare Function flInit Lib "TestFlash.dll" (ByVal port As Integer, ByVal xtal As Integer, ByVal delays As Integer, ByVal transport As Integer) As Integer
Declare Function flInitSpiUnlock Lib "TestFlash.dll" (ByVal port As Integer, ByVal xtal As Integer, ByVal delays As Integer, ByVal transport As Integer, ByVal unlockKey As String) As Integer
Declare Function flmOpen Lib "TestFlash.dll" (ByVal deviceMask As Integer, ByVal xtal As Integer, ByVal transport As Integer) As Integer
Declare Function flmOpenSpiUnlock Lib "TestFlash.dll" (ByVal deviceMask As Integer, ByVal xtal As Integer, ByVal transport As Integer, ByVal unlockKey As String) As Integer
Declare Function flInitTrans Lib "TestFlash.dll" (ByVal trans As String, ByVal xtal As Integer, ByVal delays As Integer) As Integer
Declare Function flInitSpiUnlockTrans Lib "TestFlash.dll" (ByVal trans As String, ByVal xtal As Integer, ByVal delays As Integer, ByVal unlockKey As String) As Integer
Declare Function flmOpenTrans Lib "TestFlash.dll" (ByVal deviceMask As Integer, ByVal trans As String, ByVal xtal As Integer) As Integer
Declare Function flmOpenSpiUnlockTrans Lib "TestFlash.dll" (ByVal deviceMask As Integer, ByVal trans As String, ByVal xtal As Integer, ByVal unlockKey As String) As Integer
Declare Function flReadProgramFiles Lib "TestFlash.dll" (ByVal filename As String) As Integer
Declare Function flmReadProgramFiles Lib "TestFlash.dll" (ByVal filename As String) As Integer
Declare Function flProgramBlock Lib "TestFlash.dll" () As Integer
Declare Function flmProgramBlock Lib "TestFlash.dll" (ByVal deviceMask As Integer, ByVal eraseFirst As Byte, ByVal verifyAfter As Byte, ByVal restartAfter As Byte) As Integer
Declare Function flErase Lib "TestFlash.dll" () As Integer
Declare Function flmEraseBlock Lib "TestFlash.dll" (ByVal deviceMask As Integer) As Integer
Declare Function flmEraseSpawn Lib "TestFlash.dll" (ByVal deviceMask As Integer) As Integer
Declare Function flGangProgramBlock Lib "TestFlash.dll" (ByVal deviceMask As Short, ByVal eraseFirst As Byte, ByVal restartAfter As Byte, ByVal skipUnused As Byte) As Integer
Declare Function flGetDetectedDevices Lib "TestFlash.dll" () As Short
Declare Function flGetBitErrorField Lib "TestFlash.dll" () As Short
Declare Function flmGetBitErrorField Lib "TestFlash.dll" () As Integer
Declare Function flProgramSpawn Lib "TestFlash.dll" () As Integer
Declare Function flmProgramSpawn Lib "TestFlash.dll" (ByVal deviceMask As Integer, ByVal eraseFirst As Byte, ByVal verifyAfter As Byte, ByVal restartAfter As Byte) As Integer
Declare Function flGangProgramSpawn Lib "TestFlash.dll" (ByVal deviceMask As Short, ByVal eraseFirst As Byte, ByVal restartAfter As Byte, ByVal skipUnused As Byte) As Integer
Declare Function flGetProgress Lib "TestFlash.dll" () As Integer
Declare Function flmGetDeviceProgress Lib "TestFlash.dll" (ByVal device As Integer) As Integer
Declare Function flGetLastError Lib "TestFlash.dll" () As Integer
Declare Function flmGetLastError Lib "TestFlash.dll" () As Integer
Declare Function flmGetDeviceError Lib "TestFlash.dll" (ByVal device As Integer) As Integer
Declare Function flResetAndStart Lib "TestFlash.dll" () As Integer
Declare Function flmResetAndStart Lib "TestFlash.dll" (ByVal deviceMask As Integer) As Integer
Declare Sub flClose Lib "TestFlash.dll" ()
Declare Sub flmClose Lib "TestFlash.dll" (ByVal deviceMask As Integer)
Declare Function flGetVersion Lib "TestFlash.dll" (ByVal versionStr As StringBuilder) As Integer
Declare Function flmGetVersion Lib "TestFlash.dll" (ByVal versionStr As StringBuilder) As Integer
Declare Function flStopProcessor Lib "TestFlash.dll" () As Integer
Declare Function flmStopProcessor Lib "TestFlash.dll" (ByVal deviceMask As Integer) As Integer
Declare Function flGetDownloadTime Lib "TestFlash.dll" () As Integer
Declare Function flmGetDeviceDownloadTime Lib "TestFlash.dll" (ByVal device As Integer) As Integer
Declare Function flGetAvailableSpiPorts Lib "TestFlash.dll" (ByRef maxLen As Short, ByVal ports As StringBuilder, ByVal trans As StringBuilder, ByRef count As Short) As Integer
Declare Function flmGetAvailableSpiPorts Lib "TestFlash.dll" (ByRef maxLen As Short, ByVal ports As StringBuilder, ByVal trans As StringBuilder, ByRef count As Short) As Integer
Declare Function flmConvertSpiPort Lib "TestFlash.dll" (ByVal transIn As String, ByVal transOut As StringBuilder, ByRef device As Integer) As Integer
Declare Function flGetFirmwareIds Lib "TestFlash.dll" (ByVal source As Byte, ByRef loaderId As Integer, ByVal loaderName As StringBuilder, ByRef stackId As Integer, ByVal stackName As StringBuilder, ByVal maxNameLen As Short) As Integer
Declare Function flmGetDeviceFirmwareIds Lib "TestFlash.dll" (ByVal device As Integer, ByRef loaderId As Integer, ByVal loaderName As StringBuilder, ByRef stackId As Integer, ByVal stackName As StringBuilder, ByVal maxNameLen As Short) As Integer
Declare Function flmGetFileFirmwareIds Lib "TestFlash.dll" (ByRef loaderId As Integer, ByVal loaderName As StringBuilder, ByRef stackId As Integer, ByVal stackName As StringBuilder, ByVal maxNameLen As Short) As Integer
Declare Function flVerify Lib "TestFlash.dll" () As Integer
Declare Function flmVerifyBlock Lib "TestFlash.dll" (ByVal deviceMask As Integer, ByVal restartAfter As Byte) As Integer
Declare Function flmVerifySpawn Lib "TestFlash.dll" (ByVal deviceMask As Integer, ByVal restartAfter As Byte) As Integer
Declare Function flGetFlashInfo Lib "TestFlash.dll" (ByRef sectors As Short, ByRef sizeMbits As Short, ByRef manId As Integer, ByRef devId As Integer) As Integer
Declare Function flmGetDeviceFlashInfo Lib "TestFlash.dll" (ByVal device As Integer, ByRef sectors As Short, ByRef sizeMbits As Short, ByRef manId As Integer, ByRef devId As Integer) As Integer
Declare Function flSetFlashType Lib "TestFlash.dll" (ByVal aType As Byte) As Integer
Declare Function flmSetFlashType Lib "TestFlash.dll" (ByVal deviceMask As Integer, ByVal aType As Byte) As Integer
Declare Function open_ps Lib "TestFlash.dll" (ByVal port As Integer, ByVal device As Integer) As Integer
Declare Function close_ps Lib "TestFlash.dll" () As Integer
Declare Sub set_stores Lib "TestFlash.dll" (ByVal store As Short)
Declare Function write_ps Lib "TestFlash.dll" (ByVal key As Short, ByRef data As Short, ByVal aLen As Short) As Integer
Declare Function write_ps_verify Lib "TestFlash.dll" (ByVal key As Short, ByRef data As Short, ByVal aLen As Short) As Integer
Declare Function read_ps Lib "TestFlash.dll" (ByVal key As Short, ByRef data As Short, ByVal maxlen As Short, ByRef aLen As Short) As Integer
Declare Function clear_ps Lib "TestFlash.dll" (ByVal key As Short) As Integer
Declare Function factory_set Lib "TestFlash.dll" () As Integer
Declare Function e2_device Lib "TestFlash.dll" (ByVal log2bytes As Short, ByVal addrmask As Short) As Integer
Declare Function get_firmware_id Lib "TestFlash.dll" (ByRef id As Integer, ByRef nameBuffer As Short, ByVal length As Integer) As Integer

' DEPRECATED FUNCTIONS

Declare Function init_flash Lib "TestFlash.dll" Alias "flInit" (ByVal port As Integer, ByVal xtal As Integer, ByVal delays As Integer, ByVal transport As Integer) As Integer
Declare Function read_program_files Lib "TestFlash.dll" Alias "flReadProgramFiles" (ByVal filename As String) As Integer
Declare Function program_flash_block Lib "TestFlash.dll" Alias "flProgramBlock" () As Integer
Declare Function erase_flash Lib "TestFlash.dll" Alias "flErase" () As Integer
Declare Function gang_program_flash_block Lib "TestFlash.dll" Alias "flGangProgramBlock" (ByVal deviceMask As Short, ByVal eraseFirst As Byte, ByVal restartAfter As Byte, ByVal skipUnused As Byte) As Integer
Declare Function get_bit_error_field Lib "TestFlash.dll" Alias "flGetBitErrorField" () As Short
Declare Function program_flash_spawn Lib "TestFlash.dll" Alias "flProgramSpawn" () As Integer
Declare Function gang_program_flash_spawn Lib "TestFlash.dll" Alias "flGangProgramSpawn" (ByVal deviceMask As Short, ByVal eraseFirst As Byte, ByVal restartAfter As Byte, ByVal skipUnused As Byte) As Integer
Declare Function get_spawned_progress Lib "TestFlash.dll" Alias "flGetProgress" () As Integer
Declare Function get_spawned_error Lib "TestFlash.dll" Alias "flGetLastError" () As Integer
Declare Function reset_and_start Lib "TestFlash.dll" Alias "flResetAndStart" () As Integer
Declare Sub close_flash Lib "TestFlash.dll" Alias "flClose" ()
Declare Function get_version Lib "TestFlash.dll" Alias "flGetVersion" (ByVal versionStr As StringBuilder) As Integer
End Module
