' TestEngineAPI.vb : Declares the DLL functions for vb7.
' Generated by C:\work_bluesuite_2_5\p4\common\hosttools\bluesuite_2_5\prodtest\scripts\extract_tt_api.pl from TestEngine.h;  at 03/02/14 - 11:36:54

Imports System.Text

Module TestEngine
Declare Function teGetVersion Lib "TestEngine.dll" (ByVal versionStr As StringBuilder) As Integer
Declare Function openTestEngine Lib "TestEngine.dll" (ByVal transport As Integer, ByVal transportDevice As String, ByVal dataRate As Integer, ByVal retryTimeOut As Integer, ByVal usbTimeOut As Integer) As Integer
Declare Function openTestEngineSpi Lib "TestEngine.dll" (ByVal port As Integer, ByVal multi As Integer, ByVal transport As Integer) As Integer
Declare Function openTestEngineSpiUnlock Lib "TestEngine.dll" (ByVal port As Integer, ByVal multi As Integer, ByVal transport As Integer, ByVal unlockKey As String) As Integer
Declare Function openTestEngineSpiTrans Lib "TestEngine.dll" (ByVal trans As String, ByVal multi As Integer) As Integer
Declare Function openTestEngineSpiUnlockTrans Lib "TestEngine.dll" (ByVal trans As String, ByVal multi As Integer, ByVal unlockKey As String) As Integer
Declare Function closeTestEngine Lib "TestEngine.dll" (ByVal handle As Integer) As Integer
Declare Function teGetLastError Lib "TestEngine.dll" (ByVal handle As Integer) As Integer
Declare Function bccmdSetColdReset Lib "TestEngine.dll" (ByVal handle As Integer, ByVal usbTimeout As Integer) As Integer
Declare Function bccmdSetWarmReset Lib "TestEngine.dll" (ByVal handle As Integer, ByVal usbTimeout As Integer) As Integer
Declare Function radiotestPause Lib "TestEngine.dll" (ByVal handle As Integer) As Integer
Declare Function radiotestDeepSleep Lib "TestEngine.dll" (ByVal handle As Integer) As Integer
Declare Function radiotestPcmExtLb Lib "TestEngine.dll" (ByVal handle As Integer, ByVal pcm_mode As Short) As Integer
Declare Function radiotestPcmExtLbIf Lib "TestEngine.dll" (ByVal handle As Integer, ByVal pcm_mode As Short, ByVal pcm_if As Short) As Integer
Declare Function radiotestPcmLb Lib "TestEngine.dll" (ByVal handle As Integer, ByVal pcm_mode As Short) As Integer
Declare Function radiotestPcmLbIf Lib "TestEngine.dll" (ByVal handle As Integer, ByVal pcm_mode As Short, ByVal pcm_if As Short) As Integer
Declare Function radiotestPcmTimingIn Lib "TestEngine.dll" (ByVal handle As Integer, ByVal pio_out As Short, ByVal pcm_in As Short) As Integer
Declare Function radiotestPcmTimingInIf Lib "TestEngine.dll" (ByVal handle As Integer, ByVal pio_out As Short, ByVal pcm_in As Short, ByVal pcm_if As Short) As Integer
Declare Function radiotestPcmTone Lib "TestEngine.dll" (ByVal handle As Integer, ByVal freq As Short, ByVal ampl As Short, ByVal dc As Short) As Integer
Declare Function radiotestPcmToneIf Lib "TestEngine.dll" (ByVal handle As Integer, ByVal freq As Short, ByVal ampl As Short, ByVal dc As Short, ByVal pcm_if As Short) As Integer
Declare Function radiotestPcmToneStereo Lib "TestEngine.dll" (ByVal handle As Integer, ByVal freq As Short, ByVal ampl As Short, ByVal dc As Short, ByVal channel As Short) As Integer
Declare Function radiotestCtsRtsLb Lib "TestEngine.dll" (ByVal handle As Integer) As Integer
Declare Function radiotestRadioStatus Lib "TestEngine.dll" (ByVal handle As Integer) As Integer
Declare Function hqGetRadioStatus Lib "TestEngine.dll" (ByVal handle As Integer, ByVal r As Short, ByVal timeout As Integer) As Integer
Declare Function radiotestRadioStatusArray Lib "TestEngine.dll" (ByVal handle As Integer) As Integer
Declare Function hqGetRadioStatusArray Lib "TestEngine.dll" (ByVal handle As Integer, ByVal r As Short, ByVal timeout As Integer) As Integer
Declare Function bccmdMemoryGet Lib "TestEngine.dll" (ByVal handle As Integer, ByVal baseAddr As Short, ByVal dataLength As Short, ByVal data As Short) As Integer
Declare Function bccmdMemorySet Lib "TestEngine.dll" (ByVal handle As Integer, ByVal baseAddr As Short, ByVal dataLength As Short, ByVal data As Short) As Integer
Declare Function bccmdGetBuildId Lib "TestEngine.dll" (ByVal handle As Integer, ByRef buildid As Short) As Integer
Declare Function bccmdBuildName Lib "TestEngine.dll" (ByVal handle As Integer, ByVal name As StringBuilder, ByVal max_len As Short, ByRef length As Short) As Integer
Declare Function bccmdGetChipVersion Lib "TestEngine.dll" (ByVal handle As Integer, ByRef chipver As Short) As Integer
Declare Function bccmdGetChipRevision Lib "TestEngine.dll" (ByVal handle As Integer, ByRef chiprev As Short) As Integer
Declare Function bccmdGetChipAnaVer Lib "TestEngine.dll" (ByVal handle As Integer, ByRef major As Byte, ByRef minor As Byte, ByRef vari As Byte) As Integer
Declare Function bccmdRouteClock Lib "TestEngine.dll" (ByVal handle As Integer) As Integer
Declare Function bccmdRssiAcl Lib "TestEngine.dll" (ByVal handle As Integer, ByVal connectionHandle As Short, ByRef rssi As Short) As Integer
Declare Function bccmdSetPio Lib "TestEngine.dll" (ByVal handle As Integer, ByVal mask As Short, ByVal port As Short) As Integer
Declare Function bccmdGetPio Lib "TestEngine.dll" (ByVal handle As Integer, ByRef mask As Short, ByRef port As Short) As Integer
Declare Function bccmdMapPio32 Lib "TestEngine.dll" (ByVal handle As Integer, ByVal mask As Integer, ByVal pios As Integer, ByRef errLines As Integer) As Integer
Declare Function bccmdSetPio32 Lib "TestEngine.dll" (ByVal handle As Integer, ByVal mask As Integer, ByVal direction As Integer, ByVal value As Integer, ByRef errLines As Integer) As Integer
Declare Function bccmdGetPio32 Lib "TestEngine.dll" (ByVal handle As Integer, ByRef direction As Integer, ByRef value As Integer) As Integer
Declare Function bccmdGetAdc Lib "TestEngine.dll" (ByVal handle As Integer, ByVal adc As Short, ByRef result As Short) As Integer
Declare Function bccmdGetAio Lib "TestEngine.dll" (ByVal handle As Integer, ByVal aio As Short, ByRef result As Short, ByRef numBits As Byte) As Integer
Declare Function bccmdBC5MMGetBatteryVoltage Lib "TestEngine.dll" (ByVal handle As Integer, ByRef voltage As Short) As Integer
Declare Function bccmdGetFirmwareCheckMask Lib "TestEngine.dll" (ByVal handle As Integer, ByRef mask As Short) As Integer
Declare Function bccmdGetFirmwareCheck Lib "TestEngine.dll" (ByVal handle As Integer, ByRef check As Short) As Integer
Declare Function bccmdGetExternalClockPeriod Lib "TestEngine.dll" (ByVal handle As Integer, ByRef period As Short) As Integer
Declare Function bccmdEnableDeviceConnect Lib "TestEngine.dll" (ByVal handle As Integer) As Integer
Declare Function bccmdEnableDeviceUnderTestMode Lib "TestEngine.dll" (ByVal handle As Integer) As Integer
Declare Function radiotestStereoCodecLB Lib "TestEngine.dll" (ByVal handle As Integer, ByVal sampleRate As Short, ByVal reroute As Short) As Integer
Declare Function radiotestTxstart Lib "TestEngine.dll" (ByVal handle As Integer, ByVal frequency As Short, ByVal intPA As Short, ByVal extPA As Short, ByVal modulation As Short) As Integer
Declare Function radiotestTxdata1 Lib "TestEngine.dll" (ByVal handle As Integer, ByVal frequency As Short, ByVal intPA As Short, ByVal extPA As Short) As Integer
Declare Function radiotestTxdata2 Lib "TestEngine.dll" (ByVal handle As Integer, ByVal countrycode As Short, ByVal intPA As Short, ByVal extPA As Short) As Integer
Declare Function radiotestTxdata3 Lib "TestEngine.dll" (ByVal handle As Integer, ByVal frequency As Short, ByVal intPA As Short, ByVal extPA As Short) As Integer
Declare Function radiotestTxdata4 Lib "TestEngine.dll" (ByVal handle As Integer, ByVal frequency As Short, ByVal intPA As Short, ByVal extPA As Short) As Integer
Declare Function radiotestCfgTxPower Lib "TestEngine.dll" (ByVal handle As Integer, ByVal power As Short) As Integer
Declare Function radiotestRxstart1 Lib "TestEngine.dll" (ByVal handle As Integer, ByVal frequency As Short, ByVal hiside As Byte, ByVal rx_attenuation As Short) As Integer
Declare Function radiotestRxstart2 Lib "TestEngine.dll" (ByVal handle As Integer, ByVal frequency As Short, ByVal hiside As Byte, ByVal rx_attenuation As Short, ByVal sample_size As Short) As Integer
Declare Function hqGetRssi Lib "TestEngine.dll" (ByVal handle As Integer, ByVal timeout As Integer, ByVal max_size As Short, ByVal r As Short) As Integer
Declare Function radiotestBer1 Lib "TestEngine.dll" (ByVal handle As Integer, ByVal frequency As Short, ByVal hiside As Byte, ByVal rx_attenuation As Short, ByVal sampleSize As Integer) As Integer
Declare Function radiotestBer2 Lib "TestEngine.dll" (ByVal handle As Integer, ByVal country_code As Short, ByVal hiside As Byte, ByVal rx_attenuation As Short, ByVal sampleSize As Integer) As Integer
Declare Function radiotestBerLoopback Lib "TestEngine.dll" (ByVal handle As Integer, ByVal frequency As Short, ByVal intPA As Short, ByVal extPA As Short, ByVal sampleSize As Integer) As Integer
Declare Function radiotestRxLoopback Lib "TestEngine.dll" (ByVal handle As Integer, ByVal frequency As Short, ByVal intPA As Short, ByVal extPA As Short) As Integer
Declare Function radiotestLoopback Lib "TestEngine.dll" (ByVal handle As Integer, ByVal frequency As Short, ByVal intPA As Short, ByVal extPA As Short) As Integer
Declare Function hqGetBer Lib "TestEngine.dll" (ByVal handle As Integer, ByVal timeout As Integer, ByVal r As Integer) As Integer
Declare Function radiotestRxdata1 Lib "TestEngine.dll" (ByVal handle As Integer, ByVal frequency As Short, ByVal hiside As Byte, ByVal rx_attenuation As Short) As Integer
Declare Function radiotestRxdata2 Lib "TestEngine.dll" (ByVal handle As Integer, ByVal countrycode As Short, ByVal hiside As Byte, ByVal rx_attenuation As Short) As Integer
Declare Function hqGetRxdata Lib "TestEngine.dll" (ByVal handle As Integer, ByVal timeout As Integer, ByVal r As Short) As Integer
Declare Function radiotestCfgFreq Lib "TestEngine.dll" (ByVal handle As Integer, ByVal txrxinterval As Short, ByVal loopback As Short, ByVal report As Short) As Integer
Declare Function radiotestCfgFreqMs Lib "TestEngine.dll" (ByVal handle As Integer, ByVal txrxinterval As Short, ByVal loopback As Short, ByVal report As Short) As Integer
Declare Function radiotestCfgPkt Lib "TestEngine.dll" (ByVal handle As Integer, ByVal aType As Short, ByVal size As Short) As Integer
Declare Function radiotestCfgBitError Lib "TestEngine.dll" (ByVal handle As Integer, ByVal sampleSize As Integer, ByVal reset As Byte) As Integer
Declare Function radiotestCfgTxPaAtten Lib "TestEngine.dll" (ByVal handle As Integer, ByVal atten As Short) As Integer
Declare Function radiotestCfgXtalFtrim Lib "TestEngine.dll" (ByVal handle As Integer, ByVal ftrim As Short) As Integer
Declare Function radiotestCalcXtalOffset Lib "TestEngine.dll" (ByVal nominalFreqMhz As Double, ByVal actualFreqMhz As Double, ByRef offset As Short) As Integer
Declare Function radiotestCfgUapLap Lib "TestEngine.dll" (ByVal handle As Integer, ByVal uap As Short, ByVal lap As Integer) As Integer
Declare Function radiotestCfgIqTrim Lib "TestEngine.dll" (ByVal handle As Integer, ByVal trim As Short) As Integer
Declare Function radiotestCfgTxIf Lib "TestEngine.dll" (ByVal handle As Integer, ByVal offset As Short) As Integer
Declare Function radiotestCfgTxTrim Lib "TestEngine.dll" (ByVal handle As Integer, ByVal am_addr As Short) As Integer
Declare Function radiotestCfgLoLvl Lib "TestEngine.dll" (ByVal handle As Integer, ByVal lo_lvl As Short) As Integer
Declare Function radiotestCfgHoppingSeq Lib "TestEngine.dll" (ByVal handle As Integer, ByVal channels As Short) As Integer
Declare Function radiotestSettle Lib "TestEngine.dll" (ByVal handle As Integer, ByVal start As Short, ByVal aEnd As Short) As Integer
Declare Function hqGetSettle Lib "TestEngine.dll" (ByVal handle As Integer, ByVal r As Short) As Integer
Declare Function get_freq_offset Lib "TestEngine.dll" (ByVal handle As Integer, ByRef offset As Double, ByVal sample_size As Integer) As Integer
Declare Function bccmdSetEeprom Lib "TestEngine.dll" (ByVal handle As Integer, ByVal log2bytes As Short, ByVal addrMask As Short) As Integer
Declare Function psReadBdAddr Lib "TestEngine.dll" (ByVal handle As Integer, ByRef lap As Integer, ByRef uap As Byte, ByRef nap As Short) As Integer
Declare Function psRead Lib "TestEngine.dll" (ByVal handle As Integer, ByVal psKey As Short, ByVal store As Short, ByVal arrayLen As Short, ByVal data As Short, ByRef aLen As Short) As Integer
Declare Function psClear Lib "TestEngine.dll" (ByVal handle As Integer, ByVal psKey As Short, ByVal store As Short) As Integer
Declare Function psClearAll Lib "TestEngine.dll" (ByVal handle As Integer, ByVal store As Short) As Integer
Declare Function psFactorySet Lib "TestEngine.dll" (ByVal handle As Integer) As Integer
Declare Function psFactoryRestoreAll Lib "TestEngine.dll" (ByVal handle As Integer) As Integer
Declare Function psFactoryRestore Lib "TestEngine.dll" (ByVal handle As Integer) As Integer
Declare Function psSize Lib "TestEngine.dll" (ByVal handle As Integer, ByVal psKey As Short, ByVal store As Short, ByRef size As Short) As Integer
Declare Function psWrite Lib "TestEngine.dll" (ByVal handle As Integer, ByVal psKey As Short, ByVal store As Short, ByVal length As Short, ByVal data As Short) As Integer
Declare Function psWriteVerify Lib "TestEngine.dll" (ByVal handle As Integer, ByVal psKey As Short, ByVal store As Short, ByVal length As Short, ByVal data As Short) As Integer
Declare Function psWriteBdAddr Lib "TestEngine.dll" (ByVal handle As Integer, ByVal lap As Integer, ByVal uap As Integer, ByVal nap As Integer) As Integer
Declare Function psReadModuleId Lib "TestEngine.dll" (ByVal handle As Integer, ByRef moduleId As Integer) As Integer
Declare Function psReadXtalFtrim Lib "TestEngine.dll" (ByVal handle As Integer, ByRef fTrim As Short) As Integer
Declare Function psWriteXtalFtrim Lib "TestEngine.dll" (ByVal handle As Integer, ByVal fTrim As Short) As Integer
Declare Function psReadXtalOffset Lib "TestEngine.dll" (ByVal handle As Integer, ByRef offset As Short) As Integer
Declare Function psWriteXtalOffset Lib "TestEngine.dll" (ByVal handle As Integer, ByVal offset As Short) As Integer
Declare Function psWriteModuleSecurityCode Lib "TestEngine.dll" (ByVal handle As Integer, ByVal code As Short) As Integer
Declare Function psWriteModuleId Lib "TestEngine.dll" (ByVal handle As Integer, ByVal moduleId As Integer) As Integer
Declare Function psWriteBaudrate Lib "TestEngine.dll" (ByVal handle As Integer, ByVal value As Short) As Integer
Declare Function psWriteRadiotestFirstTrimTime Lib "TestEngine.dll" (ByVal handle As Integer, ByVal time As Integer) As Integer
Declare Function psReadRadiotestFirstTrimTime Lib "TestEngine.dll" (ByVal handle As Integer, ByRef time As Integer) As Integer
Declare Function psWriteRadiotestLoLvlTrimEnable Lib "TestEngine.dll" (ByVal handle As Integer, ByVal state As Short) As Integer
Declare Function psReadRadiotestLoLvlTrimEnable Lib "TestEngine.dll" (ByVal handle As Integer, ByRef state As Short) As Integer
Declare Function psWriteRadiotestSubsequentTrimTime Lib "TestEngine.dll" (ByVal handle As Integer, ByVal time As Integer) As Integer
Declare Function psReadRadiotestSubsequentTrimTime Lib "TestEngine.dll" (ByVal handle As Integer, ByRef time As Integer) As Integer
Declare Function psWriteHostInterface Lib "TestEngine.dll" (ByVal handle As Integer, ByVal transport As Short) As Integer
Declare Function psReadHostInterface Lib "TestEngine.dll" (ByVal handle As Integer, ByRef transport As Short) As Integer
Declare Function psWriteUsbAttributes Lib "TestEngine.dll" (ByVal handle As Integer, ByVal bmAttributes As Short) As Integer
Declare Function psWriteDPlusPullup Lib "TestEngine.dll" (ByVal handle As Integer, ByVal pioPin As Short) As Integer
Declare Function psWriteUsbMaxPower Lib "TestEngine.dll" (ByVal handle As Integer, ByVal maxPower As Short) As Integer
Declare Function psWritePioProtectMask Lib "TestEngine.dll" (ByVal handle As Integer, ByVal mask As Short) As Integer
Declare Function psReadPioProtectMask Lib "TestEngine.dll" (ByVal handle As Integer, ByRef mask As Short) As Integer
Declare Function psWriteTxOffsetHalfMhz Lib "TestEngine.dll" (ByVal handle As Integer, ByVal offset As Short) As Integer
Declare Function psReadTxOffsetHalfMhz Lib "TestEngine.dll" (ByVal handle As Integer, ByRef offset As Short) As Integer
Declare Function psWriteUsrValue Lib "TestEngine.dll" (ByVal handle As Integer, ByVal userNo As Short, ByVal length As Short, ByVal data As Short) As Integer
Declare Function psReadUsrValue Lib "TestEngine.dll" (ByVal handle As Integer, ByVal userNo As Short, ByVal maxLen As Short, ByRef length As Short, ByVal data As Short) As Integer
Declare Function psWritePowerTable Lib "TestEngine.dll" (ByVal handle As Integer, ByVal numEntries As Short, ByVal intPA As Byte, ByVal extPA As Byte, ByVal power As Integer) As Integer
Declare Function psReadPowerTable Lib "TestEngine.dll" (ByVal handle As Integer, ByVal maxSize As Integer, ByRef numEntries As Integer, ByVal intPA As Byte, ByVal extPA As Byte, ByVal power As Integer) As Integer
Declare Function psWriteVmDisable Lib "TestEngine.dll" (ByVal handle As Integer, ByVal vmDisable As Byte) As Integer
Declare Function psReadVmDisable Lib "TestEngine.dll" (ByVal handle As Integer, ByRef vmDisable As Byte) As Integer
Declare Function psMergeFromFile Lib "TestEngine.dll" (ByVal handle As Integer, ByVal filePath As String) As Integer
Declare Function hciSlave Lib "TestEngine.dll" (ByVal handle As Integer) As Integer
Declare Function hciSetAfhHostChannelClass Lib "TestEngine.dll" (ByVal handle As Integer, ByVal cClass As Byte) As Integer
Declare Function hciReadAfhChannelMap Lib "TestEngine.dll" (ByVal handle As Integer, ByVal aclHandle As Short, ByRef mode As Byte, ByVal cMap As Byte) As Integer
Declare Function hciSetEventFilterAutoacceptConnection Lib "TestEngine.dll" (ByVal handle As Integer) As Integer
Declare Function hciWriteInquiryScanActivity Lib "TestEngine.dll" (ByVal handle As Integer, ByVal inquiryscan_interval As Short, ByVal inquiryscan_window As Short) As Integer
Declare Function hciWritePageScanActivity Lib "TestEngine.dll" (ByVal handle As Integer, ByVal pagescan_interval As Short, ByVal pagescan_window As Short) As Integer
Declare Function hciWriteScanEnable Lib "TestEngine.dll" (ByVal handle As Integer, ByVal scan_enable As Byte) As Integer
Declare Function hciInquiry Lib "TestEngine.dll" (ByVal handle As Integer, ByVal inquiryLength As Byte, ByVal numResponses As Byte, ByVal lap As Integer) As Integer
Declare Function hciGetInquiryResults Lib "TestEngine.dll" (ByVal handle As Integer, ByVal lap As Integer, ByVal uap As Byte, ByVal nap As Short, ByVal clockOffset As Short, ByVal maxLen As Integer, ByRef aLen As Integer) As Integer
Declare Function hciInquiryCancel Lib "TestEngine.dll" (ByVal handle As Integer) As Integer
Declare Function hciCreateConnection Lib "TestEngine.dll" (ByVal handle As Integer, ByVal lap As Integer, ByVal uap As Byte, ByVal nap As Short, ByVal pkt_type As Short, ByRef connectionHandle As Short) As Integer
Declare Function hciCreateConnectionNoInquiry Lib "TestEngine.dll" (ByVal handle As Integer, ByVal lap As Integer, ByVal uap As Byte, ByVal nap As Short, ByVal pkt_type As Short, ByVal page_scan_rep_mode As Byte, ByVal page_scan_mode As Byte, ByVal clock_offset As Short, ByVal allow_role_switch As Byte, ByRef connectionHandle As Short) As Integer
Declare Function hciCreateScoConnection Lib "TestEngine.dll" (ByVal handle As Integer, ByVal aclConnectionHandle As Short, ByVal pkt_type As Short, ByRef scoConnectionHandle As Short) As Integer
Declare Function hciSetupScoConnection Lib "TestEngine.dll" (ByVal handle As Integer, ByVal aclConnectionHandle As Short, ByVal txBandwidth As Integer, ByVal rxBandwidth As Integer, ByVal maxLatency As Short, ByVal voiceSetting As Short, ByVal retransEffort As Byte, ByVal pktType As Short, ByRef scoConnectionHandle As Short) As Integer
Declare Function hciReadVoiceSetting Lib "TestEngine.dll" (ByVal handle As Integer, ByRef voiceSetting As Short) As Integer
Declare Function hciWriteVoiceSetting Lib "TestEngine.dll" (ByVal handle As Integer, ByVal voiceSetting As Short) As Integer
Declare Function hciWriteLinkPolicySettings Lib "TestEngine.dll" (ByVal handle As Integer, ByVal connection_handle As Short, ByVal link_policy_settings As Short) As Integer
Declare Function hciSendAclFile Lib "TestEngine.dll" (ByVal handle As Integer, ByVal connHandle As Short, ByVal fileName As String) As Integer
Declare Function hciSendAclData Lib "TestEngine.dll" (ByVal handle As Integer, ByVal connHandle As Short, ByVal data As Byte, ByVal length As Short) As Integer
Declare Function hciGetAclData Lib "TestEngine.dll" (ByVal handle As Integer, ByVal data As Byte, ByRef numBytes As Integer) As Integer
Declare Function hciGetAclBytesRead Lib "TestEngine.dll" (ByVal handle As Integer, ByRef numBytes As Integer) As Integer
Declare Function hciGetAclFileName Lib "TestEngine.dll" (ByVal handle As Integer, ByVal fileName As StringBuilder, ByRef length As Integer) As Integer
Declare Function hciGetAclState Lib "TestEngine.dll" (ByVal handle As Integer, ByRef state As Integer) As Integer
Declare Function hciResetAclState Lib "TestEngine.dll" (ByVal handle As Integer) As Integer
Declare Function hciReset Lib "TestEngine.dll" (ByVal handle As Integer) As Integer
Declare Function bccmdGetAnaXtalFtrim Lib "TestEngine.dll" (ByVal handle As Integer, ByRef ftrim As Short) As Integer
Declare Function bccmdSetAnaXtalFtrim Lib "TestEngine.dll" (ByVal handle As Integer, ByVal ftrim As Short) As Integer
Declare Function hciSniffMode Lib "TestEngine.dll" (ByVal handle As Integer, ByVal connection_handle As Short, ByVal sniff_max_interval As Short, ByVal sniff_min_interval As Short, ByVal sniff_attempt As Short, ByVal sniff_timeout As Short) As Integer
Declare Function hciExitSniff Lib "TestEngine.dll" (ByVal handle As Integer, ByVal connection_handle As Short) As Integer
Declare Function hciDisconnect Lib "TestEngine.dll" (ByVal handle As Integer, ByVal connection_handle As Short) As Integer
Declare Function hciGetConnectionHandle Lib "TestEngine.dll" (ByVal handle As Integer, ByVal lap As Integer, ByVal uap As Byte, ByVal nap As Short, ByRef connectionHandle As Short) As Integer
Declare Function hciConnectionStatus Lib "TestEngine.dll" (ByVal handle As Integer, ByVal connection_handle As Short) As Integer
Declare Function hciEnableDeviceUnderTestMode Lib "TestEngine.dll" (ByVal handle As Integer) As Integer
Declare Function hciGetLinkQuality Lib "TestEngine.dll" (ByVal handle As Integer, ByVal connection_handle As Short, ByRef quality As Byte) As Integer
Declare Function hciReadRemoteVersionInformation Lib "TestEngine.dll" (ByVal handle As Integer, ByVal connection_handle As Short, ByVal r As Integer) As Integer
Declare Function hciReadRemoteNameRequest Lib "TestEngine.dll" (ByVal handle As Integer, ByVal lap As Integer, ByVal uap As Byte, ByVal nap As Short, ByVal page_scan_repetition_mode As Byte, ByVal page_scan_offset As Byte, ByVal clock_offset As Short, ByVal r As StringBuilder) As Integer
Declare Function dmRegisterReq Lib "TestEngine.dll" (ByVal handle As Integer) As Integer
Declare Function dmSlave Lib "TestEngine.dll" (ByVal handle As Integer) As Integer
Declare Function dmEnableDeviceUnderTestMode Lib "TestEngine.dll" (ByVal handle As Integer) As Integer
Declare Function dmWritePageScanActivity Lib "TestEngine.dll" (ByVal handle As Integer, ByVal pagescan_interval As Short, ByVal pagescan_window As Short) As Integer
Declare Function dmWriteInquiryScanActivity Lib "TestEngine.dll" (ByVal handle As Integer, ByVal inquiryscan_interval As Short, ByVal inquiryscan_window As Short) As Integer
Declare Function dmWriteScanEnable Lib "TestEngine.dll" (ByVal handle As Integer, ByVal scan_enable As Byte) As Integer
Declare Function dmSetEventFilterAutoacceptConnection Lib "TestEngine.dll" (ByVal handle As Integer) As Integer
Declare Function bccmdBc3PsuTrim Lib "TestEngine.dll" (ByVal handle As Integer, ByVal data As Short) As Integer
Declare Function bccmdChargerPsuTrim Lib "TestEngine.dll" (ByVal handle As Integer, ByVal trim As Short) As Integer
Declare Function bccmdBc3BuckReg Lib "TestEngine.dll" (ByVal handle As Integer, ByVal data As Short) As Integer
Declare Function bccmdPsuSmpsEnable Lib "TestEngine.dll" (ByVal handle As Integer, ByVal reg As Short) As Integer
Declare Function bccmdBc3MicEn Lib "TestEngine.dll" (ByVal handle As Integer, ByVal data As Short) As Integer
Declare Function bccmdPsuHvLinearEnable Lib "TestEngine.dll" (ByVal handle As Integer, ByVal reg As Short) As Integer
Declare Function bccmdBc3Led0 Lib "TestEngine.dll" (ByVal handle As Integer, ByVal data As Short) As Integer
Declare Function bccmdLedEnable Lib "TestEngine.dll" (ByVal handle As Integer, ByVal led As Short, ByVal state As Short) As Integer
Declare Function bccmdLed0Enable Lib "TestEngine.dll" (ByVal handle As Integer, ByVal state As Short) As Integer
Declare Function bccmdBc3Led1 Lib "TestEngine.dll" (ByVal handle As Integer, ByVal data As Short) As Integer
Declare Function bccmdLed1Enable Lib "TestEngine.dll" (ByVal handle As Integer, ByVal state As Short) As Integer
Declare Function bccmdChargerStatus Lib "TestEngine.dll" (ByVal handle As Integer, ByRef state As Short) As Integer
Declare Function bccmdChargerDisable Lib "TestEngine.dll" (ByVal handle As Integer, ByVal state As Short) As Integer
Declare Function bccmdChargerSuppressLed0 Lib "TestEngine.dll" (ByVal handle As Integer, ByVal state As Short) As Integer
Declare Function hciCreateConnectionNoWait Lib "TestEngine.dll" (ByVal handle As Integer, ByVal lap As Integer, ByVal uap As Byte, ByVal nap As Short, ByVal pktType As Short, ByVal pageScanRepMode As Byte, ByVal pageScanMode As Byte, ByVal clockOffset As Short, ByVal allowRoleSwitch As Byte) As Integer
Declare Function hciWriteAuthenticationEnable Lib "TestEngine.dll" (ByVal handle As Integer, ByVal enable As Byte) As Integer
Declare Function hciLinkKeyRequestNegativeReply Lib "TestEngine.dll" (ByVal handle As Integer, ByVal lap As Integer, ByVal uap As Byte, ByVal nap As Short) As Integer
Declare Function hciWaitForConnectionComplete Lib "TestEngine.dll" (ByVal handle As Integer, ByRef connHandle As Short) As Integer
Declare Function hciWaitForLinkKeyRequest Lib "TestEngine.dll" (ByVal handle As Integer, ByRef lap As Integer, ByRef uap As Byte, ByRef nap As Short) As Integer
Declare Function hciWaitForPinCodeRequest Lib "TestEngine.dll" (ByVal handle As Integer, ByRef lap As Integer, ByRef uap As Byte, ByRef nap As Short) As Integer
Declare Function hciWaitForEncryptionChange Lib "TestEngine.dll" (ByVal handle As Integer, ByRef enable As Byte) As Integer
Declare Function hciPinCodeRequestReply Lib "TestEngine.dll" (ByVal handle As Integer, ByVal lap As Integer, ByVal uap As Byte, ByVal nap As Short, ByVal pinCodeLength As Byte, ByVal pinCode As Byte) As Integer
Declare Function hciSetConnectionEncryption Lib "TestEngine.dll" (ByVal handle As Integer, ByVal connHandle As Short, ByVal enable As Byte) As Integer
Declare Function vmWrite Lib "TestEngine.dll" (ByVal handle As Integer, ByVal data As Short) As Integer
Declare Function vmRead Lib "TestEngine.dll" (ByVal handle As Integer, ByVal data As Short, ByVal timeout As Short) As Integer
Declare Function bccmdSetSingleChan Lib "TestEngine.dll" (ByVal handle As Integer, ByVal channel As Short) As Integer
Declare Function bccmdSetHoppingOn Lib "TestEngine.dll" (ByVal handle As Integer) As Integer
Declare Function bccmdFmSwitchPower Lib "TestEngine.dll" (ByVal handle As Integer, ByVal powerOn As Byte) As Integer
Declare Function bccmdFmSetFreq Lib "TestEngine.dll" (ByVal handle As Integer, ByVal freqKHz As Integer) As Integer
Declare Function bccmdFmGetRssi Lib "TestEngine.dll" (ByVal handle As Integer, ByRef rssi As Byte) As Integer
Declare Function bccmdFmGetSnr Lib "TestEngine.dll" (ByVal handle As Integer, ByRef snr As Short) As Integer
Declare Function bccmdFmGetIfOffset Lib "TestEngine.dll" (ByVal handle As Integer, ByRef offset As Short) As Integer
Declare Function bccmdFmGetStatus Lib "TestEngine.dll" (ByVal handle As Integer, ByRef status As Byte) As Integer
Declare Function bccmdFmSetupAudio Lib "TestEngine.dll" (ByVal handle As Integer, ByVal route As Byte, ByVal gain As Byte, ByVal channel As Byte) As Integer
Declare Function bccmdFmVerifyRDSPi Lib "TestEngine.dll" (ByVal handle As Integer, ByVal pi As Short, ByVal timeoutMs As Short, ByRef matched As Byte) As Integer
Declare Function bccmdFmTxSwitchPower Lib "TestEngine.dll" (ByVal handle As Integer, ByVal powerOn As Byte) As Integer
Declare Function bccmdFmTxSetFreq Lib "TestEngine.dll" (ByVal handle As Integer, ByVal freqKHz As Integer) As Integer
Declare Function bccmdFmTxSetPowerLevel Lib "TestEngine.dll" (ByVal handle As Integer, ByVal powerLevel As Short) As Integer
Declare Function bccmdFmTxSetupAudio Lib "TestEngine.dll" (ByVal handle As Integer, ByVal route As Byte, ByVal audioGain As Short) As Integer
Declare Function bccmdDisconnectAudio Lib "TestEngine.dll" (ByVal handle As Integer) As Integer
Declare Function bccmdDirectChargerPsuTrim Lib "TestEngine.dll" (ByVal handle As Integer, ByVal trim As Short) As Integer
Declare Function teSupportsHq Lib "TestEngine.dll" (ByVal handle As Integer, ByRef hqSupported As Byte) As Integer
Declare Function bccmdSetAuxDac Lib "TestEngine.dll" (ByVal handle As Integer, ByVal enable As Byte, ByVal level As Byte) As Integer
Declare Function bccmdSetMicBiasIf Lib "TestEngine.dll" (ByVal handle As Integer, ByVal instance As Byte, ByVal enable As Byte, ByVal voltage As Byte) As Integer
Declare Function bccmdSetMicBias Lib "TestEngine.dll" (ByVal handle As Integer, ByVal enable As Byte, ByVal voltage As Byte, ByVal current As Byte, ByVal enableLowPowerMode As Byte) As Integer
Declare Function teGetAvailableSpiPorts Lib "TestEngine.dll" (ByRef maxLen As Short, ByVal ports As StringBuilder, ByVal trans As StringBuilder, ByRef count As Short) As Integer
Declare Function bccmdProvokeFault Lib "TestEngine.dll" (ByVal handle As Integer, ByVal faultCode As Short) As Integer
Declare Function hqGetFaultReports Lib "TestEngine.dll" (ByVal handle As Integer, ByVal maxReports As Short, ByVal codes As Short, ByVal timestamps As Integer, ByVal repeats As Short, ByRef numReports As Short, ByVal timeout As Integer) As Integer
Declare Function teGetFaultDesc Lib "TestEngine.dll" (ByVal handle As Integer, ByVal faultCode As Short, ByVal desc As StringBuilder) As Integer
Declare Function bccmdSetMapScoPcm Lib "TestEngine.dll" (ByVal handle As Integer, ByVal enable As Byte) As Integer
Declare Function bccmdGetVrefConstant Lib "TestEngine.dll" (ByVal handle As Integer, ByRef vref As Short) As Integer
Declare Function bccmdGetVrefAdc Lib "TestEngine.dll" (ByVal handle As Integer, ByRef result As Short, ByRef numBits As Byte) As Integer
Declare Function bccmdBC5FMGetI2CState Lib "TestEngine.dll" (ByVal handle As Integer, ByRef sda As Byte, ByRef scl As Byte) As Integer
Declare Function refEpGetRssiDbm Lib "TestEngine.dll" (ByVal handle As Integer, ByVal freqMHz As Short, ByVal rssiChip As Double, ByRef rssiDbm As Double) As Integer
Declare Function refEpGetPaLevel Lib "TestEngine.dll" (ByVal handle As Integer, ByVal freqMHz As Short, ByVal targetPowerDbm As Double, ByRef intPa As Short, ByRef powerDbm As Double) As Integer
Declare Function refEpWriteCalDataFile Lib "TestEngine.dll" (ByVal handle As Integer, ByVal filePath As String) As Integer
Declare Function refEpLoadCalDataFile Lib "TestEngine.dll" (ByVal handle As Integer, ByVal filePath As String) As Integer
Declare Function bccmdGetVmStatus Lib "TestEngine.dll" (ByVal handle As Integer, ByRef status As Short, ByRef exitCode As Short) As Integer
Declare Function bccmdI2CTransfer Lib "TestEngine.dll" (ByVal handle As Integer, ByVal slaveAddr As Short, ByVal txOctets As Short, ByVal rxOctets As Short, ByVal restart As Byte, ByVal data As Byte, ByRef octets As Short) As Integer
Declare Function radiotestBle Lib "TestEngine.dll" (ByVal handle As Integer, ByVal command As Short, ByVal channel As Byte, ByVal txLength As Byte, ByVal txPayload As Byte) As Integer
Declare Function hqGetBleRxPktCount Lib "TestEngine.dll" (ByVal handle As Integer, ByVal timeout As Integer, ByRef pktCount As Short) As Integer
Declare Function bccmdGetChargerTrims Lib "TestEngine.dll" (ByVal handle As Integer, ByRef chgRefTrim As Short, ByRef hVrefTrim As Short, ByRef rTrim As Short, ByRef iTrim As Short, ByRef iExtTrim As Short, ByRef iTermTrim As Short, ByRef vFastTrim As Short, ByRef hystTrim As Short) As Integer
Declare Function bccmdCapSenseRead Lib "TestEngine.dll" (ByVal handle As Integer, ByVal mask As Short, ByVal values As Short) As Integer
Declare Function bccmdSetSpiLockCustomerKey Lib "TestEngine.dll" (ByVal handle As Integer, ByVal custKey As Integer) As Integer
Declare Function bccmdGetSpiLockStatus Lib "TestEngine.dll" (ByVal handle As Integer, ByRef status As Short) As Integer
Declare Function bccmdSpiLockInitiateLock Lib "TestEngine.dll" (ByVal handle As Integer) As Integer
Declare Function teGetChipDisplayName Lib "TestEngine.dll" (ByVal handle As Integer, ByVal maxLen As Integer, ByVal name As StringBuilder) As Integer

' DEPRECATED FUNCTIONS

Declare Function bccmdPsuBuckReg Lib "TestEngine.dll" Alias "bccmdPsuSmpsEnable" (ByVal handle As Integer, ByVal reg As Short) As Integer
Declare Function bccmdPsuMicEn Lib "TestEngine.dll" Alias "bccmdPsuHvLinearEnable" (ByVal handle As Integer, ByVal reg As Short) As Integer
Declare Function bccmdLed0 Lib "TestEngine.dll" Alias "bccmdLed0Enable" (ByVal handle As Integer, ByVal state As Short) As Integer
Declare Function bccmdLed1 Lib "TestEngine.dll" Alias "bccmdLed1Enable" (ByVal handle As Integer, ByVal state As Short) As Integer
Declare Function bccmdChargerSupressLed0 Lib "TestEngine.dll" Alias "bccmdChargerSuppressLed0" (ByVal handle As Integer, ByVal state As Short) As Integer
End Module
