// HidDfuAPI.cs : Declares the DLL functions for C#.
// Generated by C:\work_bluesuite_2_5\p4\common\hosttools\bluesuite_2_5\prodtest\scripts\extract_tt_api.pl from HidDfu.h;  at 03/02/14 - 11:13:42

using System;
using System.Runtime.InteropServices;
using System.Text;

namespace HidDfuAPI
{
    public class HidDfu
    {
#if PocketPC || WindowsCE
        const CharSet charset = CharSet.Auto;
        const CallingConvention calling_convention = CallingConvention.Winapi;
#else
        const CharSet charset = CharSet.Ansi;
        const CallingConvention calling_convention = CallingConvention.StdCall;
#endif

        [DllImport("HidDfu.dll", EntryPoint="hidDfuGetVersion",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int hidDfuGetVersion(out ushort major, out ushort minor, out ushort release, out ushort build);

        [DllImport("HidDfu.dll", EntryPoint="hidDfuConnect",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int hidDfuConnect(ushort vid, ushort pid, ushort usage, ushort usagePage);

        [DllImport("HidDfu.dll", EntryPoint="hidDfuDisconnect",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int hidDfuDisconnect();

        [DllImport("HidDfu.dll", EntryPoint="hidDfuBackup",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int hidDfuBackup(String fileName);
        [DllImport("HidDfu.dll", EntryPoint="hidDfuBackup",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int hidDfuBackup(byte [] fileName);

        [DllImport("HidDfu.dll", EntryPoint="hidDfuUpgrade",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int hidDfuUpgrade(String fileName);
        [DllImport("HidDfu.dll", EntryPoint="hidDfuUpgrade",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int hidDfuUpgrade(byte [] fileName);

        [DllImport("HidDfu.dll", EntryPoint="hidDfuResetDevice",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int hidDfuResetDevice();

        [DllImport("HidDfu.dll", EntryPoint="hidDfuGetProgress",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern byte hidDfuGetProgress();

        [DllImport("HidDfu.dll", EntryPoint="hidDfuGetResult",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int hidDfuGetResult();

        [DllImport("HidDfu.dll", EntryPoint="hidDfuGetLastError",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern IntPtr hidDfuGetLastError();

        [DllImport("HidDfu.dll", EntryPoint="hidDfuSendCommand",
                CharSet=charset, CallingConvention=calling_convention)]
        public static extern int hidDfuSendCommand(ref byte data, uint length);

    }
}
