' TestFlashAPI_05.vb : Declares the DLL functions for vb2005.
' Generated by C:\work_bluesuite_2_5\p4\common\hosttools\bluesuite_2_5\prodtest\scripts\extract_tt_api.pl from TestFlash.h; TestPS.h;  at 03/02/14 - 11:39:57

Imports System.Text
Imports System.Runtime.InteropServices

Module TestFlash
    Public Const TFL_OK As Integer = 0
    Public Const TFL_ERROR As Integer = -1
    Public Const TFL_DEVICE_ERROR As Integer = -2
    Public Const TFL_SPI_LPT As Integer = 1
    Public Const TFL_SPI_USB As Integer = 2
    Public Const TFL_CHIP As Integer = 0
    Public Const TFL_FILE As Integer = 1
    Public Const TFL_ERROR_OPEN_FAILED As Integer = 4097
    Public Const TFL_ERROR_DEVICE_OPEN As Integer = 4098
    Public Const TFL_ERROR_DEVICE_NOT_OPEN As Integer = 4099
    Public Const TFL_ERROR_DEVICE_BUSY As Integer = 4100
    Public Const TFL_ERROR_THREAD_ERROR As Integer = 4101
    Public Const TFL_ERROR_RESET_FAIL As Integer = 4102
    Public Const TFL_ERROR_XTAL_INVALID As Integer = 4103
    Public Const TFL_ERROR_WRONG_TRANS As Integer = 4104
    Public Const TFL_ERROR_SPIUNLOCK As Integer = 4105
    Public Const TFL_MAX_DEVICES As Integer = 32
    Public Const TFL_ALL_DEVICES As Integer = -1
    Public Const TFL_TYPE_STANDARD As Integer = 0
    Public Const TFL_TYPE_SPIF As Integer = 1
    Public Const TFL_TYPE_SQIF As Integer = 2
    <DllImport("TestFlash.dll", EntryPoint:="flInit", _
    CharSet:=CharSet.Ansi, CallingConvention:=CallingConvention.StdCall)> _
    Function flInit (ByVal port As Integer, ByVal xtal As Integer, ByVal delays As Integer, ByVal transport As Integer) As Integer
    End Function
    <DllImport("TestFlash.dll", EntryPoint:="flInitSpiUnlock", _
    CharSet:=CharSet.Ansi, CallingConvention:=CallingConvention.StdCall)> _
    Function flInitSpiUnlock (ByVal port As Integer, ByVal xtal As Integer, ByVal delays As Integer, ByVal transport As Integer, ByVal unlockKey As String) As Integer
    End Function
    <DllImport("TestFlash.dll", EntryPoint:="flmOpen", _
    CharSet:=CharSet.Ansi, CallingConvention:=CallingConvention.StdCall)> _
    Function flmOpen (ByVal deviceMask As UInteger, ByVal xtal As Integer, ByVal transport As Integer) As Integer
    End Function
    <DllImport("TestFlash.dll", EntryPoint:="flmOpenSpiUnlock", _
    CharSet:=CharSet.Ansi, CallingConvention:=CallingConvention.StdCall)> _
    Function flmOpenSpiUnlock (ByVal deviceMask As UInteger, ByVal xtal As Integer, ByVal transport As Integer, ByVal unlockKey As String) As Integer
    End Function
    <DllImport("TestFlash.dll", EntryPoint:="flInitTrans", _
    CharSet:=CharSet.Ansi, CallingConvention:=CallingConvention.StdCall)> _
    Function flInitTrans (ByVal trans As String, ByVal xtal As Integer, ByVal delays As Integer) As Integer
    End Function
    <DllImport("TestFlash.dll", EntryPoint:="flInitSpiUnlockTrans", _
    CharSet:=CharSet.Ansi, CallingConvention:=CallingConvention.StdCall)> _
    Function flInitSpiUnlockTrans (ByVal trans As String, ByVal xtal As Integer, ByVal delays As Integer, ByVal unlockKey As String) As Integer
    End Function
    <DllImport("TestFlash.dll", EntryPoint:="flmOpenTrans", _
    CharSet:=CharSet.Ansi, CallingConvention:=CallingConvention.StdCall)> _
    Function flmOpenTrans (ByVal deviceMask As UInteger, ByVal trans As String, ByVal xtal As Integer) As Integer
    End Function
    <DllImport("TestFlash.dll", EntryPoint:="flmOpenSpiUnlockTrans", _
    CharSet:=CharSet.Ansi, CallingConvention:=CallingConvention.StdCall)> _
    Function flmOpenSpiUnlockTrans (ByVal deviceMask As UInteger, ByVal trans As String, ByVal xtal As Integer, ByVal unlockKey As String) As Integer
    End Function
    <DllImport("TestFlash.dll", EntryPoint:="flReadProgramFiles", _
    CharSet:=CharSet.Ansi, CallingConvention:=CallingConvention.StdCall)> _
    Function flReadProgramFiles (ByVal filename As String) As Integer
    End Function
    <DllImport("TestFlash.dll", EntryPoint:="flmReadProgramFiles", _
    CharSet:=CharSet.Ansi, CallingConvention:=CallingConvention.StdCall)> _
    Function flmReadProgramFiles (ByVal filename As String) As Integer
    End Function
    <DllImport("TestFlash.dll", EntryPoint:="flProgramBlock", _
    CharSet:=CharSet.Ansi, CallingConvention:=CallingConvention.StdCall)> _
    Function flProgramBlock () As Integer
    End Function
    <DllImport("TestFlash.dll", EntryPoint:="flmProgramBlock", _
    CharSet:=CharSet.Ansi, CallingConvention:=CallingConvention.StdCall)> _
    Function flmProgramBlock (ByVal deviceMask As UInteger, ByVal eraseFirst As Byte, ByVal verifyAfter As Byte, ByVal restartAfter As Byte) As Integer
    End Function
    <DllImport("TestFlash.dll", EntryPoint:="flErase", _
    CharSet:=CharSet.Ansi, CallingConvention:=CallingConvention.StdCall)> _
    Function flErase () As Integer
    End Function
    <DllImport("TestFlash.dll", EntryPoint:="flmEraseBlock", _
    CharSet:=CharSet.Ansi, CallingConvention:=CallingConvention.StdCall)> _
    Function flmEraseBlock (ByVal deviceMask As UInteger) As Integer
    End Function
    <DllImport("TestFlash.dll", EntryPoint:="flmEraseSpawn", _
    CharSet:=CharSet.Ansi, CallingConvention:=CallingConvention.StdCall)> _
    Function flmEraseSpawn (ByVal deviceMask As UInteger) As Integer
    End Function
    <DllImport("TestFlash.dll", EntryPoint:="flGangProgramBlock", _
    CharSet:=CharSet.Ansi, CallingConvention:=CallingConvention.StdCall)> _
    Function flGangProgramBlock (ByVal deviceMask As UShort, ByVal eraseFirst As Byte, ByVal restartAfter As Byte, ByVal skipUnused As Byte) As Integer
    End Function
    <DllImport("TestFlash.dll", EntryPoint:="flGetDetectedDevices", _
    CharSet:=CharSet.Ansi, CallingConvention:=CallingConvention.StdCall)> _
    Function flGetDetectedDevices () As UShort
    End Function
    <DllImport("TestFlash.dll", EntryPoint:="flGetBitErrorField", _
    CharSet:=CharSet.Ansi, CallingConvention:=CallingConvention.StdCall)> _
    Function flGetBitErrorField () As UShort
    End Function
    <DllImport("TestFlash.dll", EntryPoint:="flmGetBitErrorField", _
    CharSet:=CharSet.Ansi, CallingConvention:=CallingConvention.StdCall)> _
    Function flmGetBitErrorField () As UInteger
    End Function
    <DllImport("TestFlash.dll", EntryPoint:="flProgramSpawn", _
    CharSet:=CharSet.Ansi, CallingConvention:=CallingConvention.StdCall)> _
    Function flProgramSpawn () As Integer
    End Function
    <DllImport("TestFlash.dll", EntryPoint:="flmProgramSpawn", _
    CharSet:=CharSet.Ansi, CallingConvention:=CallingConvention.StdCall)> _
    Function flmProgramSpawn (ByVal deviceMask As UInteger, ByVal eraseFirst As Byte, ByVal verifyAfter As Byte, ByVal restartAfter As Byte) As Integer
    End Function
    <DllImport("TestFlash.dll", EntryPoint:="flGangProgramSpawn", _
    CharSet:=CharSet.Ansi, CallingConvention:=CallingConvention.StdCall)> _
    Function flGangProgramSpawn (ByVal deviceMask As UShort, ByVal eraseFirst As Byte, ByVal restartAfter As Byte, ByVal skipUnused As Byte) As Integer
    End Function
    <DllImport("TestFlash.dll", EntryPoint:="flGetProgress", _
    CharSet:=CharSet.Ansi, CallingConvention:=CallingConvention.StdCall)> _
    Function flGetProgress () As Integer
    End Function
    <DllImport("TestFlash.dll", EntryPoint:="flmGetDeviceProgress", _
    CharSet:=CharSet.Ansi, CallingConvention:=CallingConvention.StdCall)> _
    Function flmGetDeviceProgress (ByVal device As UInteger) As Integer
    End Function
    <DllImport("TestFlash.dll", EntryPoint:="flGetLastError", _
    CharSet:=CharSet.Ansi, CallingConvention:=CallingConvention.StdCall)> _
    Function flGetLastError () As Integer
    End Function
    <DllImport("TestFlash.dll", EntryPoint:="flmGetLastError", _
    CharSet:=CharSet.Ansi, CallingConvention:=CallingConvention.StdCall)> _
    Function flmGetLastError () As Integer
    End Function
    <DllImport("TestFlash.dll", EntryPoint:="flmGetDeviceError", _
    CharSet:=CharSet.Ansi, CallingConvention:=CallingConvention.StdCall)> _
    Function flmGetDeviceError (ByVal device As UInteger) As Integer
    End Function
    <DllImport("TestFlash.dll", EntryPoint:="flResetAndStart", _
    CharSet:=CharSet.Ansi, CallingConvention:=CallingConvention.StdCall)> _
    Function flResetAndStart () As Integer
    End Function
    <DllImport("TestFlash.dll", EntryPoint:="flmResetAndStart", _
    CharSet:=CharSet.Ansi, CallingConvention:=CallingConvention.StdCall)> _
    Function flmResetAndStart (ByVal deviceMask As UInteger) As Integer
    End Function
    <DllImport("TestFlash.dll", EntryPoint:="flClose", _
    CharSet:=CharSet.Ansi, CallingConvention:=CallingConvention.StdCall)> _
    Sub flClose ()
    End Sub
    <DllImport("TestFlash.dll", EntryPoint:="flmClose", _
    CharSet:=CharSet.Ansi, CallingConvention:=CallingConvention.StdCall)> _
    Sub flmClose (ByVal deviceMask As UInteger)
    End Sub
    <DllImport("TestFlash.dll", EntryPoint:="flGetVersion", _
    CharSet:=CharSet.Ansi, CallingConvention:=CallingConvention.StdCall)> _
    Function flGetVersion (ByVal versionStr As StringBuilder) As Integer
    End Function
    <DllImport("TestFlash.dll", EntryPoint:="flmGetVersion", _
    CharSet:=CharSet.Ansi, CallingConvention:=CallingConvention.StdCall)> _
    Function flmGetVersion (ByVal versionStr As StringBuilder) As Integer
    End Function
    <DllImport("TestFlash.dll", EntryPoint:="flStopProcessor", _
    CharSet:=CharSet.Ansi, CallingConvention:=CallingConvention.StdCall)> _
    Function flStopProcessor () As Integer
    End Function
    <DllImport("TestFlash.dll", EntryPoint:="flmStopProcessor", _
    CharSet:=CharSet.Ansi, CallingConvention:=CallingConvention.StdCall)> _
    Function flmStopProcessor (ByVal deviceMask As UInteger) As Integer
    End Function
    <DllImport("TestFlash.dll", EntryPoint:="flGetDownloadTime", _
    CharSet:=CharSet.Ansi, CallingConvention:=CallingConvention.StdCall)> _
    Function flGetDownloadTime () As UInteger
    End Function
    <DllImport("TestFlash.dll", EntryPoint:="flmGetDeviceDownloadTime", _
    CharSet:=CharSet.Ansi, CallingConvention:=CallingConvention.StdCall)> _
    Function flmGetDeviceDownloadTime (ByVal device As UInteger) As UInteger
    End Function
    <DllImport("TestFlash.dll", EntryPoint:="flGetAvailableSpiPorts", _
    CharSet:=CharSet.Ansi, CallingConvention:=CallingConvention.StdCall)> _
    Function flGetAvailableSpiPorts (ByRef maxLen As UShort, ByVal ports As StringBuilder, ByVal trans As StringBuilder, ByRef count As UShort) As Integer
    End Function
    <DllImport("TestFlash.dll", EntryPoint:="flmGetAvailableSpiPorts", _
    CharSet:=CharSet.Ansi, CallingConvention:=CallingConvention.StdCall)> _
    Function flmGetAvailableSpiPorts (ByRef maxLen As UShort, ByVal ports As StringBuilder, ByVal trans As StringBuilder, ByRef count As UShort) As Integer
    End Function
    <DllImport("TestFlash.dll", EntryPoint:="flmConvertSpiPort", _
    CharSet:=CharSet.Ansi, CallingConvention:=CallingConvention.StdCall)> _
    Function flmConvertSpiPort (ByVal transIn As String, ByVal transOut As StringBuilder, ByRef device As UInteger) As Integer
    End Function
    <DllImport("TestFlash.dll", EntryPoint:="flGetFirmwareIds", _
    CharSet:=CharSet.Ansi, CallingConvention:=CallingConvention.StdCall)> _
    Function flGetFirmwareIds (ByVal source As Byte, ByRef loaderId As UInteger, ByVal loaderName As StringBuilder, ByRef stackId As UInteger, ByVal stackName As StringBuilder, ByVal maxNameLen As UShort) As Integer
    End Function
    <DllImport("TestFlash.dll", EntryPoint:="flmGetDeviceFirmwareIds", _
    CharSet:=CharSet.Ansi, CallingConvention:=CallingConvention.StdCall)> _
    Function flmGetDeviceFirmwareIds (ByVal device As UInteger, ByRef loaderId As UInteger, ByVal loaderName As StringBuilder, ByRef stackId As UInteger, ByVal stackName As StringBuilder, ByVal maxNameLen As UShort) As Integer
    End Function
    <DllImport("TestFlash.dll", EntryPoint:="flmGetFileFirmwareIds", _
    CharSet:=CharSet.Ansi, CallingConvention:=CallingConvention.StdCall)> _
    Function flmGetFileFirmwareIds (ByRef loaderId As UInteger, ByVal loaderName As StringBuilder, ByRef stackId As UInteger, ByVal stackName As StringBuilder, ByVal maxNameLen As UShort) As Integer
    End Function
    <DllImport("TestFlash.dll", EntryPoint:="flVerify", _
    CharSet:=CharSet.Ansi, CallingConvention:=CallingConvention.StdCall)> _
    Function flVerify () As Integer
    End Function
    <DllImport("TestFlash.dll", EntryPoint:="flmVerifyBlock", _
    CharSet:=CharSet.Ansi, CallingConvention:=CallingConvention.StdCall)> _
    Function flmVerifyBlock (ByVal deviceMask As UInteger, ByVal restartAfter As Byte) As Integer
    End Function
    <DllImport("TestFlash.dll", EntryPoint:="flmVerifySpawn", _
    CharSet:=CharSet.Ansi, CallingConvention:=CallingConvention.StdCall)> _
    Function flmVerifySpawn (ByVal deviceMask As UInteger, ByVal restartAfter As Byte) As Integer
    End Function
    <DllImport("TestFlash.dll", EntryPoint:="flGetFlashInfo", _
    CharSet:=CharSet.Ansi, CallingConvention:=CallingConvention.StdCall)> _
    Function flGetFlashInfo (ByRef sectors As UShort, ByRef sizeMbits As UShort, ByRef manId As UInteger, ByRef devId As UInteger) As Integer
    End Function
    <DllImport("TestFlash.dll", EntryPoint:="flmGetDeviceFlashInfo", _
    CharSet:=CharSet.Ansi, CallingConvention:=CallingConvention.StdCall)> _
    Function flmGetDeviceFlashInfo (ByVal device As UInteger, ByRef sectors As UShort, ByRef sizeMbits As UShort, ByRef manId As UInteger, ByRef devId As UInteger) As Integer
    End Function
    <DllImport("TestFlash.dll", EntryPoint:="flSetFlashType", _
    CharSet:=CharSet.Ansi, CallingConvention:=CallingConvention.StdCall)> _
    Function flSetFlashType (ByVal aType As Byte) As Integer
    End Function
    <DllImport("TestFlash.dll", EntryPoint:="flmSetFlashType", _
    CharSet:=CharSet.Ansi, CallingConvention:=CallingConvention.StdCall)> _
    Function flmSetFlashType (ByVal deviceMask As UInteger, ByVal aType As Byte) As Integer
    End Function
    <DllImport("TestFlash.dll", EntryPoint:="open_ps", _
    CharSet:=CharSet.Ansi, CallingConvention:=CallingConvention.StdCall)> _
    Function open_ps (ByVal port As Integer, ByVal device As Integer) As Integer
    End Function
    <DllImport("TestFlash.dll", EntryPoint:="close_ps", _
    CharSet:=CharSet.Ansi, CallingConvention:=CallingConvention.StdCall)> _
    Function close_ps () As Integer
    End Function
    <DllImport("TestFlash.dll", EntryPoint:="set_stores", _
    CharSet:=CharSet.Ansi, CallingConvention:=CallingConvention.StdCall)> _
    Sub set_stores (ByVal store As UShort)
    End Sub
    <DllImport("TestFlash.dll", EntryPoint:="write_ps", _
    CharSet:=CharSet.Ansi, CallingConvention:=CallingConvention.StdCall)> _
    Function write_ps (ByVal key As UShort, ByRef data As UShort, ByVal aLen As UShort) As Integer
    End Function
    <DllImport("TestFlash.dll", EntryPoint:="write_ps_verify", _
    CharSet:=CharSet.Ansi, CallingConvention:=CallingConvention.StdCall)> _
    Function write_ps_verify (ByVal key As UShort, ByRef data As UShort, ByVal aLen As UShort) As Integer
    End Function
    <DllImport("TestFlash.dll", EntryPoint:="read_ps", _
    CharSet:=CharSet.Ansi, CallingConvention:=CallingConvention.StdCall)> _
    Function read_ps (ByVal key As UShort, ByRef data As UShort, ByVal maxlen As UShort, ByRef aLen As UShort) As Integer
    End Function
    <DllImport("TestFlash.dll", EntryPoint:="clear_ps", _
    CharSet:=CharSet.Ansi, CallingConvention:=CallingConvention.StdCall)> _
    Function clear_ps (ByVal key As UShort) As Integer
    End Function
    <DllImport("TestFlash.dll", EntryPoint:="factory_set", _
    CharSet:=CharSet.Ansi, CallingConvention:=CallingConvention.StdCall)> _
    Function factory_set () As Integer
    End Function
    <DllImport("TestFlash.dll", EntryPoint:="e2_device", _
    CharSet:=CharSet.Ansi, CallingConvention:=CallingConvention.StdCall)> _
    Function e2_device (ByVal log2bytes As UShort, ByVal addrmask As UShort) As Integer
    End Function
    <DllImport("TestFlash.dll", EntryPoint:="get_firmware_id", _
    CharSet:=CharSet.Ansi, CallingConvention:=CallingConvention.StdCall)> _
    Function get_firmware_id (ByRef id As Integer, ByRef nameBuffer As UShort, ByVal length As UInteger) As Integer
    End Function

' DEPRECATED FUNCTIONS

Declare Function init_flash Lib "TestFlash.dll" Alias "flInit" (ByVal port As Integer, ByVal xtal As Integer, ByVal delays As Integer, ByVal transport As Integer) As Integer
Declare Function read_program_files Lib "TestFlash.dll" Alias "flReadProgramFiles" (ByVal filename As String) As Integer
Declare Function program_flash_block Lib "TestFlash.dll" Alias "flProgramBlock" () As Integer
Declare Function erase_flash Lib "TestFlash.dll" Alias "flErase" () As Integer
Declare Function gang_program_flash_block Lib "TestFlash.dll" Alias "flGangProgramBlock" (ByVal deviceMask As UShort, ByVal eraseFirst As Byte, ByVal restartAfter As Byte, ByVal skipUnused As Byte) As Integer
Declare Function get_bit_error_field Lib "TestFlash.dll" Alias "flGetBitErrorField" () As UShort
Declare Function program_flash_spawn Lib "TestFlash.dll" Alias "flProgramSpawn" () As Integer
Declare Function gang_program_flash_spawn Lib "TestFlash.dll" Alias "flGangProgramSpawn" (ByVal deviceMask As UShort, ByVal eraseFirst As Byte, ByVal restartAfter As Byte, ByVal skipUnused As Byte) As Integer
Declare Function get_spawned_progress Lib "TestFlash.dll" Alias "flGetProgress" () As Integer
Declare Function get_spawned_error Lib "TestFlash.dll" Alias "flGetLastError" () As Integer
Declare Function reset_and_start Lib "TestFlash.dll" Alias "flResetAndStart" () As Integer
Declare Sub close_flash Lib "TestFlash.dll" Alias "flClose" ()
Declare Function get_version Lib "TestFlash.dll" Alias "flGetVersion" (ByVal versionStr As StringBuilder) As Integer
End Module
