' TestEngineAPI.bas : Declares the DLL functions for vb6.
' Generated by C:\work_bluesuite_2_5\p4\common\hosttools\bluesuite_2_5\prodtest\scripts\extract_tt_api.pl from TestEngine.h;  at 03/02/14 - 11:36:54

Declare Function teGetVersion Lib "TestEngine.dll" (ByVal versionStr As String) As Long
Declare Function openTestEngine Lib "TestEngine.dll" (ByVal transport As Long, ByVal transportDevice As String, ByVal dataRate As Long, ByVal retryTimeOut As Long, ByVal usbTimeOut As Long) As Long
Declare Function openTestEngineSpi Lib "TestEngine.dll" (ByVal port As Long, ByVal multi As Long, ByVal transport As Long) As Long
Declare Function openTestEngineSpiUnlock Lib "TestEngine.dll" (ByVal port As Long, ByVal multi As Long, ByVal transport As Long, ByVal unlockKey As String) As Long
Declare Function openTestEngineSpiTrans Lib "TestEngine.dll" (ByVal trans As String, ByVal multi As Long) As Long
Declare Function openTestEngineSpiUnlockTrans Lib "TestEngine.dll" (ByVal trans As String, ByVal multi As Long, ByVal unlockKey As String) As Long
Declare Function closeTestEngine Lib "TestEngine.dll" (ByVal handle As Long) As Long
Declare Function teGetLastError Lib "TestEngine.dll" (ByVal handle As Long) As Long
Declare Function bccmdSetColdReset Lib "TestEngine.dll" (ByVal handle As Long, ByVal usbTimeout As Long) As Long
Declare Function bccmdSetWarmReset Lib "TestEngine.dll" (ByVal handle As Long, ByVal usbTimeout As Long) As Long
Declare Function radiotestPause Lib "TestEngine.dll" (ByVal handle As Long) As Long
Declare Function radiotestDeepSleep Lib "TestEngine.dll" (ByVal handle As Long) As Long
Declare Function radiotestPcmExtLb Lib "TestEngine.dll" (ByVal handle As Long, ByVal pcm_mode As Integer) As Long
Declare Function radiotestPcmExtLbIf Lib "TestEngine.dll" (ByVal handle As Long, ByVal pcm_mode As Integer, ByVal pcm_if As Integer) As Long
Declare Function radiotestPcmLb Lib "TestEngine.dll" (ByVal handle As Long, ByVal pcm_mode As Integer) As Long
Declare Function radiotestPcmLbIf Lib "TestEngine.dll" (ByVal handle As Long, ByVal pcm_mode As Integer, ByVal pcm_if As Integer) As Long
Declare Function radiotestPcmTimingIn Lib "TestEngine.dll" (ByVal handle As Long, ByVal pio_out As Integer, ByVal pcm_in As Integer) As Long
Declare Function radiotestPcmTimingInIf Lib "TestEngine.dll" (ByVal handle As Long, ByVal pio_out As Integer, ByVal pcm_in As Integer, ByVal pcm_if As Integer) As Long
Declare Function radiotestPcmTone Lib "TestEngine.dll" (ByVal handle As Long, ByVal freq As Integer, ByVal ampl As Integer, ByVal dc As Integer) As Long
Declare Function radiotestPcmToneIf Lib "TestEngine.dll" (ByVal handle As Long, ByVal freq As Integer, ByVal ampl As Integer, ByVal dc As Integer, ByVal pcm_if As Integer) As Long
Declare Function radiotestPcmToneStereo Lib "TestEngine.dll" (ByVal handle As Long, ByVal freq As Integer, ByVal ampl As Integer, ByVal dc As Integer, ByVal channel As Integer) As Long
Declare Function radiotestCtsRtsLb Lib "TestEngine.dll" (ByVal handle As Long) As Long
Declare Function radiotestRadioStatus Lib "TestEngine.dll" (ByVal handle As Long) As Long
Declare Function hqGetRadioStatus Lib "TestEngine.dll" (ByVal handle As Long, ByVal r As Integer, ByVal timeout As Long) As Long
Declare Function radiotestRadioStatusArray Lib "TestEngine.dll" (ByVal handle As Long) As Long
Declare Function hqGetRadioStatusArray Lib "TestEngine.dll" (ByVal handle As Long, ByVal r As Integer, ByVal timeout As Long) As Long
Declare Function bccmdMemoryGet Lib "TestEngine.dll" (ByVal handle As Long, ByVal baseAddr As Integer, ByVal dataLength As Integer, ByVal data As Integer) As Long
Declare Function bccmdMemorySet Lib "TestEngine.dll" (ByVal handle As Long, ByVal baseAddr As Integer, ByVal dataLength As Integer, ByVal data As Integer) As Long
Declare Function bccmdGetBuildId Lib "TestEngine.dll" (ByVal handle As Long, ByRef buildid As Integer) As Long
Declare Function bccmdBuildName Lib "TestEngine.dll" (ByVal handle As Long, ByVal name As String, ByVal max_len As Integer, ByRef length As Integer) As Long
Declare Function bccmdGetChipVersion Lib "TestEngine.dll" (ByVal handle As Long, ByRef chipver As Integer) As Long
Declare Function bccmdGetChipRevision Lib "TestEngine.dll" (ByVal handle As Long, ByRef chiprev As Integer) As Long
Declare Function bccmdGetChipAnaVer Lib "TestEngine.dll" (ByVal handle As Long, ByRef major As Byte, ByRef minor As Byte, ByRef vari As Byte) As Long
Declare Function bccmdRouteClock Lib "TestEngine.dll" (ByVal handle As Long) As Long
Declare Function bccmdRssiAcl Lib "TestEngine.dll" (ByVal handle As Long, ByVal connectionHandle As Integer, ByRef rssi As Integer) As Long
Declare Function bccmdSetPio Lib "TestEngine.dll" (ByVal handle As Long, ByVal mask As Integer, ByVal port As Integer) As Long
Declare Function bccmdGetPio Lib "TestEngine.dll" (ByVal handle As Long, ByRef mask As Integer, ByRef port As Integer) As Long
Declare Function bccmdMapPio32 Lib "TestEngine.dll" (ByVal handle As Long, ByVal mask As Long, ByVal pios As Long, ByRef errLines As Long) As Long
Declare Function bccmdSetPio32 Lib "TestEngine.dll" (ByVal handle As Long, ByVal mask As Long, ByVal direction As Long, ByVal value As Long, ByRef errLines As Long) As Long
Declare Function bccmdGetPio32 Lib "TestEngine.dll" (ByVal handle As Long, ByRef direction As Long, ByRef value As Long) As Long
Declare Function bccmdGetAdc Lib "TestEngine.dll" (ByVal handle As Long, ByVal adc As Integer, ByRef result As Integer) As Long
Declare Function bccmdGetAio Lib "TestEngine.dll" (ByVal handle As Long, ByVal aio As Integer, ByRef result As Integer, ByRef numBits As Byte) As Long
Declare Function bccmdBC5MMGetBatteryVoltage Lib "TestEngine.dll" (ByVal handle As Long, ByRef voltage As Integer) As Long
Declare Function bccmdGetFirmwareCheckMask Lib "TestEngine.dll" (ByVal handle As Long, ByRef mask As Integer) As Long
Declare Function bccmdGetFirmwareCheck Lib "TestEngine.dll" (ByVal handle As Long, ByRef check As Integer) As Long
Declare Function bccmdGetExternalClockPeriod Lib "TestEngine.dll" (ByVal handle As Long, ByRef period As Integer) As Long
Declare Function bccmdEnableDeviceConnect Lib "TestEngine.dll" (ByVal handle As Long) As Long
Declare Function bccmdEnableDeviceUnderTestMode Lib "TestEngine.dll" (ByVal handle As Long) As Long
Declare Function radiotestStereoCodecLB Lib "TestEngine.dll" (ByVal handle As Long, ByVal sampleRate As Integer, ByVal reroute As Integer) As Long
Declare Function radiotestTxstart Lib "TestEngine.dll" (ByVal handle As Long, ByVal frequency As Integer, ByVal intPA As Integer, ByVal extPA As Integer, ByVal modulation As Integer) As Long
Declare Function radiotestTxdata1 Lib "TestEngine.dll" (ByVal handle As Long, ByVal frequency As Integer, ByVal intPA As Integer, ByVal extPA As Integer) As Long
Declare Function radiotestTxdata2 Lib "TestEngine.dll" (ByVal handle As Long, ByVal countrycode As Integer, ByVal intPA As Integer, ByVal extPA As Integer) As Long
Declare Function radiotestTxdata3 Lib "TestEngine.dll" (ByVal handle As Long, ByVal frequency As Integer, ByVal intPA As Integer, ByVal extPA As Integer) As Long
Declare Function radiotestTxdata4 Lib "TestEngine.dll" (ByVal handle As Long, ByVal frequency As Integer, ByVal intPA As Integer, ByVal extPA As Integer) As Long
Declare Function radiotestCfgTxPower Lib "TestEngine.dll" (ByVal handle As Long, ByVal power As Integer) As Long
Declare Function radiotestRxstart1 Lib "TestEngine.dll" (ByVal handle As Long, ByVal frequency As Integer, ByVal hiside As Byte, ByVal rx_attenuation As Integer) As Long
Declare Function radiotestRxstart2 Lib "TestEngine.dll" (ByVal handle As Long, ByVal frequency As Integer, ByVal hiside As Byte, ByVal rx_attenuation As Integer, ByVal sample_size As Integer) As Long
Declare Function hqGetRssi Lib "TestEngine.dll" (ByVal handle As Long, ByVal timeout As Long, ByVal max_size As Integer, ByVal r As Integer) As Long
Declare Function radiotestBer1 Lib "TestEngine.dll" (ByVal handle As Long, ByVal frequency As Integer, ByVal hiside As Byte, ByVal rx_attenuation As Integer, ByVal sampleSize As Long) As Long
Declare Function radiotestBer2 Lib "TestEngine.dll" (ByVal handle As Long, ByVal country_code As Integer, ByVal hiside As Byte, ByVal rx_attenuation As Integer, ByVal sampleSize As Long) As Long
Declare Function radiotestBerLoopback Lib "TestEngine.dll" (ByVal handle As Long, ByVal frequency As Integer, ByVal intPA As Integer, ByVal extPA As Integer, ByVal sampleSize As Long) As Long
Declare Function radiotestRxLoopback Lib "TestEngine.dll" (ByVal handle As Long, ByVal frequency As Integer, ByVal intPA As Integer, ByVal extPA As Integer) As Long
Declare Function radiotestLoopback Lib "TestEngine.dll" (ByVal handle As Long, ByVal frequency As Integer, ByVal intPA As Integer, ByVal extPA As Integer) As Long
Declare Function hqGetBer Lib "TestEngine.dll" (ByVal handle As Long, ByVal timeout As Long, ByVal r As Long) As Long
Declare Function radiotestRxdata1 Lib "TestEngine.dll" (ByVal handle As Long, ByVal frequency As Integer, ByVal hiside As Byte, ByVal rx_attenuation As Integer) As Long
Declare Function radiotestRxdata2 Lib "TestEngine.dll" (ByVal handle As Long, ByVal countrycode As Integer, ByVal hiside As Byte, ByVal rx_attenuation As Integer) As Long
Declare Function hqGetRxdata Lib "TestEngine.dll" (ByVal handle As Long, ByVal timeout As Long, ByVal r As Integer) As Long
Declare Function radiotestCfgFreq Lib "TestEngine.dll" (ByVal handle As Long, ByVal txrxinterval As Integer, ByVal loopback As Integer, ByVal report As Integer) As Long
Declare Function radiotestCfgFreqMs Lib "TestEngine.dll" (ByVal handle As Long, ByVal txrxinterval As Integer, ByVal loopback As Integer, ByVal report As Integer) As Long
Declare Function radiotestCfgPkt Lib "TestEngine.dll" (ByVal handle As Long, ByVal aType As Integer, ByVal size As Integer) As Long
Declare Function radiotestCfgBitError Lib "TestEngine.dll" (ByVal handle As Long, ByVal sampleSize As Long, ByVal reset As Byte) As Long
Declare Function radiotestCfgTxPaAtten Lib "TestEngine.dll" (ByVal handle As Long, ByVal atten As Integer) As Long
Declare Function radiotestCfgXtalFtrim Lib "TestEngine.dll" (ByVal handle As Long, ByVal ftrim As Integer) As Long
Declare Function radiotestCalcXtalOffset Lib "TestEngine.dll" (ByVal nominalFreqMhz As Double, ByVal actualFreqMhz As Double, ByRef offset As Integer) As Long
Declare Function radiotestCfgUapLap Lib "TestEngine.dll" (ByVal handle As Long, ByVal uap As Integer, ByVal lap As Long) As Long
Declare Function radiotestCfgIqTrim Lib "TestEngine.dll" (ByVal handle As Long, ByVal trim As Integer) As Long
Declare Function radiotestCfgTxIf Lib "TestEngine.dll" (ByVal handle As Long, ByVal offset As Integer) As Long
Declare Function radiotestCfgTxTrim Lib "TestEngine.dll" (ByVal handle As Long, ByVal am_addr As Integer) As Long
Declare Function radiotestCfgLoLvl Lib "TestEngine.dll" (ByVal handle As Long, ByVal lo_lvl As Integer) As Long
Declare Function radiotestCfgHoppingSeq Lib "TestEngine.dll" (ByVal handle As Long, ByVal channels As Integer) As Long
Declare Function radiotestSettle Lib "TestEngine.dll" (ByVal handle As Long, ByVal start As Integer, ByVal aEnd As Integer) As Long
Declare Function hqGetSettle Lib "TestEngine.dll" (ByVal handle As Long, ByVal r As Integer) As Long
Declare Function get_freq_offset Lib "TestEngine.dll" (ByVal handle As Long, ByRef offset As Double, ByVal sample_size As Long) As Long
Declare Function bccmdSetEeprom Lib "TestEngine.dll" (ByVal handle As Long, ByVal log2bytes As Integer, ByVal addrMask As Integer) As Long
Declare Function psReadBdAddr Lib "TestEngine.dll" (ByVal handle As Long, ByRef lap As Long, ByRef uap As Byte, ByRef nap As Integer) As Long
Declare Function psRead Lib "TestEngine.dll" (ByVal handle As Long, ByVal psKey As Integer, ByVal store As Integer, ByVal arrayLen As Integer, ByVal data As Integer, ByRef aLen As Integer) As Long
Declare Function psClear Lib "TestEngine.dll" (ByVal handle As Long, ByVal psKey As Integer, ByVal store As Integer) As Long
Declare Function psClearAll Lib "TestEngine.dll" (ByVal handle As Long, ByVal store As Integer) As Long
Declare Function psFactorySet Lib "TestEngine.dll" (ByVal handle As Long) As Long
Declare Function psFactoryRestoreAll Lib "TestEngine.dll" (ByVal handle As Long) As Long
Declare Function psFactoryRestore Lib "TestEngine.dll" (ByVal handle As Long) As Long
Declare Function psSize Lib "TestEngine.dll" (ByVal handle As Long, ByVal psKey As Integer, ByVal store As Integer, ByRef size As Integer) As Long
Declare Function psWrite Lib "TestEngine.dll" (ByVal handle As Long, ByVal psKey As Integer, ByVal store As Integer, ByVal length As Integer, ByVal data As Integer) As Long
Declare Function psWriteVerify Lib "TestEngine.dll" (ByVal handle As Long, ByVal psKey As Integer, ByVal store As Integer, ByVal length As Integer, ByVal data As Integer) As Long
Declare Function psWriteBdAddr Lib "TestEngine.dll" (ByVal handle As Long, ByVal lap As Long, ByVal uap As Long, ByVal nap As Long) As Long
Declare Function psReadModuleId Lib "TestEngine.dll" (ByVal handle As Long, ByRef moduleId As Long) As Long
Declare Function psReadXtalFtrim Lib "TestEngine.dll" (ByVal handle As Long, ByRef fTrim As Integer) As Long
Declare Function psWriteXtalFtrim Lib "TestEngine.dll" (ByVal handle As Long, ByVal fTrim As Integer) As Long
Declare Function psReadXtalOffset Lib "TestEngine.dll" (ByVal handle As Long, ByRef offset As Integer) As Long
Declare Function psWriteXtalOffset Lib "TestEngine.dll" (ByVal handle As Long, ByVal offset As Integer) As Long
Declare Function psWriteModuleSecurityCode Lib "TestEngine.dll" (ByVal handle As Long, ByVal code As Integer) As Long
Declare Function psWriteModuleId Lib "TestEngine.dll" (ByVal handle As Long, ByVal moduleId As Long) As Long
Declare Function psWriteBaudrate Lib "TestEngine.dll" (ByVal handle As Long, ByVal value As Integer) As Long
Declare Function psWriteRadiotestFirstTrimTime Lib "TestEngine.dll" (ByVal handle As Long, ByVal time As Long) As Long
Declare Function psReadRadiotestFirstTrimTime Lib "TestEngine.dll" (ByVal handle As Long, ByRef time As Long) As Long
Declare Function psWriteRadiotestLoLvlTrimEnable Lib "TestEngine.dll" (ByVal handle As Long, ByVal state As Integer) As Long
Declare Function psReadRadiotestLoLvlTrimEnable Lib "TestEngine.dll" (ByVal handle As Long, ByRef state As Integer) As Long
Declare Function psWriteRadiotestSubsequentTrimTime Lib "TestEngine.dll" (ByVal handle As Long, ByVal time As Long) As Long
Declare Function psReadRadiotestSubsequentTrimTime Lib "TestEngine.dll" (ByVal handle As Long, ByRef time As Long) As Long
Declare Function psWriteHostInterface Lib "TestEngine.dll" (ByVal handle As Long, ByVal transport As Integer) As Long
Declare Function psReadHostInterface Lib "TestEngine.dll" (ByVal handle As Long, ByRef transport As Integer) As Long
Declare Function psWriteUsbAttributes Lib "TestEngine.dll" (ByVal handle As Long, ByVal bmAttributes As Integer) As Long
Declare Function psWriteDPlusPullup Lib "TestEngine.dll" (ByVal handle As Long, ByVal pioPin As Integer) As Long
Declare Function psWriteUsbMaxPower Lib "TestEngine.dll" (ByVal handle As Long, ByVal maxPower As Integer) As Long
Declare Function psWritePioProtectMask Lib "TestEngine.dll" (ByVal handle As Long, ByVal mask As Integer) As Long
Declare Function psReadPioProtectMask Lib "TestEngine.dll" (ByVal handle As Long, ByRef mask As Integer) As Long
Declare Function psWriteTxOffsetHalfMhz Lib "TestEngine.dll" (ByVal handle As Long, ByVal offset As Integer) As Long
Declare Function psReadTxOffsetHalfMhz Lib "TestEngine.dll" (ByVal handle As Long, ByRef offset As Integer) As Long
Declare Function psWriteUsrValue Lib "TestEngine.dll" (ByVal handle As Long, ByVal userNo As Integer, ByVal length As Integer, ByVal data As Integer) As Long
Declare Function psReadUsrValue Lib "TestEngine.dll" (ByVal handle As Long, ByVal userNo As Integer, ByVal maxLen As Integer, ByRef length As Integer, ByVal data As Integer) As Long
Declare Function psWritePowerTable Lib "TestEngine.dll" (ByVal handle As Long, ByVal numEntries As Integer, ByVal intPA As Byte, ByVal extPA As Byte, ByVal power As Long) As Long
Declare Function psReadPowerTable Lib "TestEngine.dll" (ByVal handle As Long, ByVal maxSize As Long, ByRef numEntries As Long, ByVal intPA As Byte, ByVal extPA As Byte, ByVal power As Long) As Long
Declare Function psWriteVmDisable Lib "TestEngine.dll" (ByVal handle As Long, ByVal vmDisable As Byte) As Long
Declare Function psReadVmDisable Lib "TestEngine.dll" (ByVal handle As Long, ByRef vmDisable As Byte) As Long
Declare Function psMergeFromFile Lib "TestEngine.dll" (ByVal handle As Long, ByVal filePath As String) As Long
Declare Function hciSlave Lib "TestEngine.dll" (ByVal handle As Long) As Long
Declare Function hciSetAfhHostChannelClass Lib "TestEngine.dll" (ByVal handle As Long, ByVal cClass As Byte) As Long
Declare Function hciReadAfhChannelMap Lib "TestEngine.dll" (ByVal handle As Long, ByVal aclHandle As Integer, ByRef mode As Byte, ByVal cMap As Byte) As Long
Declare Function hciSetEventFilterAutoacceptConnection Lib "TestEngine.dll" (ByVal handle As Long) As Long
Declare Function hciWriteInquiryScanActivity Lib "TestEngine.dll" (ByVal handle As Long, ByVal inquiryscan_interval As Integer, ByVal inquiryscan_window As Integer) As Long
Declare Function hciWritePageScanActivity Lib "TestEngine.dll" (ByVal handle As Long, ByVal pagescan_interval As Integer, ByVal pagescan_window As Integer) As Long
Declare Function hciWriteScanEnable Lib "TestEngine.dll" (ByVal handle As Long, ByVal scan_enable As Byte) As Long
Declare Function hciInquiry Lib "TestEngine.dll" (ByVal handle As Long, ByVal inquiryLength As Byte, ByVal numResponses As Byte, ByVal lap As Long) As Long
Declare Function hciGetInquiryResults Lib "TestEngine.dll" (ByVal handle As Long, ByVal lap As Long, ByVal uap As Byte, ByVal nap As Integer, ByVal clockOffset As Integer, ByVal maxLen As Long, ByRef aLen As Long) As Long
Declare Function hciInquiryCancel Lib "TestEngine.dll" (ByVal handle As Long) As Long
Declare Function hciCreateConnection Lib "TestEngine.dll" (ByVal handle As Long, ByVal lap As Long, ByVal uap As Byte, ByVal nap As Integer, ByVal pkt_type As Integer, ByRef connectionHandle As Integer) As Long
Declare Function hciCreateConnectionNoInquiry Lib "TestEngine.dll" (ByVal handle As Long, ByVal lap As Long, ByVal uap As Byte, ByVal nap As Integer, ByVal pkt_type As Integer, ByVal page_scan_rep_mode As Byte, ByVal page_scan_mode As Byte, ByVal clock_offset As Integer, ByVal allow_role_switch As Byte, ByRef connectionHandle As Integer) As Long
Declare Function hciCreateScoConnection Lib "TestEngine.dll" (ByVal handle As Long, ByVal aclConnectionHandle As Integer, ByVal pkt_type As Integer, ByRef scoConnectionHandle As Integer) As Long
Declare Function hciSetupScoConnection Lib "TestEngine.dll" (ByVal handle As Long, ByVal aclConnectionHandle As Integer, ByVal txBandwidth As Long, ByVal rxBandwidth As Long, ByVal maxLatency As Integer, ByVal voiceSetting As Integer, ByVal retransEffort As Byte, ByVal pktType As Integer, ByRef scoConnectionHandle As Integer) As Long
Declare Function hciReadVoiceSetting Lib "TestEngine.dll" (ByVal handle As Long, ByRef voiceSetting As Integer) As Long
Declare Function hciWriteVoiceSetting Lib "TestEngine.dll" (ByVal handle As Long, ByVal voiceSetting As Integer) As Long
Declare Function hciWriteLinkPolicySettings Lib "TestEngine.dll" (ByVal handle As Long, ByVal connection_handle As Integer, ByVal link_policy_settings As Integer) As Long
Declare Function hciSendAclFile Lib "TestEngine.dll" (ByVal handle As Long, ByVal connHandle As Integer, ByVal fileName As String) As Long
Declare Function hciSendAclData Lib "TestEngine.dll" (ByVal handle As Long, ByVal connHandle As Integer, ByVal data As Byte, ByVal length As Integer) As Long
Declare Function hciGetAclData Lib "TestEngine.dll" (ByVal handle As Long, ByVal data As Byte, ByRef numBytes As Long) As Long
Declare Function hciGetAclBytesRead Lib "TestEngine.dll" (ByVal handle As Long, ByRef numBytes As Long) As Long
Declare Function hciGetAclFileName Lib "TestEngine.dll" (ByVal handle As Long, ByVal fileName As String, ByRef length As Long) As Long
Declare Function hciGetAclState Lib "TestEngine.dll" (ByVal handle As Long, ByRef state As Long) As Long
Declare Function hciResetAclState Lib "TestEngine.dll" (ByVal handle As Long) As Long
Declare Function hciReset Lib "TestEngine.dll" (ByVal handle As Long) As Long
Declare Function bccmdGetAnaXtalFtrim Lib "TestEngine.dll" (ByVal handle As Long, ByRef ftrim As Integer) As Long
Declare Function bccmdSetAnaXtalFtrim Lib "TestEngine.dll" (ByVal handle As Long, ByVal ftrim As Integer) As Long
Declare Function hciSniffMode Lib "TestEngine.dll" (ByVal handle As Long, ByVal connection_handle As Integer, ByVal sniff_max_interval As Integer, ByVal sniff_min_interval As Integer, ByVal sniff_attempt As Integer, ByVal sniff_timeout As Integer) As Long
Declare Function hciExitSniff Lib "TestEngine.dll" (ByVal handle As Long, ByVal connection_handle As Integer) As Long
Declare Function hciDisconnect Lib "TestEngine.dll" (ByVal handle As Long, ByVal connection_handle As Integer) As Long
Declare Function hciGetConnectionHandle Lib "TestEngine.dll" (ByVal handle As Long, ByVal lap As Long, ByVal uap As Byte, ByVal nap As Integer, ByRef connectionHandle As Integer) As Long
Declare Function hciConnectionStatus Lib "TestEngine.dll" (ByVal handle As Long, ByVal connection_handle As Integer) As Long
Declare Function hciEnableDeviceUnderTestMode Lib "TestEngine.dll" (ByVal handle As Long) As Long
Declare Function hciGetLinkQuality Lib "TestEngine.dll" (ByVal handle As Long, ByVal connection_handle As Integer, ByRef quality As Byte) As Long
Declare Function hciReadRemoteVersionInformation Lib "TestEngine.dll" (ByVal handle As Long, ByVal connection_handle As Integer, ByVal r As Long) As Long
Declare Function hciReadRemoteNameRequest Lib "TestEngine.dll" (ByVal handle As Long, ByVal lap As Long, ByVal uap As Byte, ByVal nap As Integer, ByVal page_scan_repetition_mode As Byte, ByVal page_scan_offset As Byte, ByVal clock_offset As Integer, ByVal r As String) As Long
Declare Function dmRegisterReq Lib "TestEngine.dll" (ByVal handle As Long) As Long
Declare Function dmSlave Lib "TestEngine.dll" (ByVal handle As Long) As Long
Declare Function dmEnableDeviceUnderTestMode Lib "TestEngine.dll" (ByVal handle As Long) As Long
Declare Function dmWritePageScanActivity Lib "TestEngine.dll" (ByVal handle As Long, ByVal pagescan_interval As Integer, ByVal pagescan_window As Integer) As Long
Declare Function dmWriteInquiryScanActivity Lib "TestEngine.dll" (ByVal handle As Long, ByVal inquiryscan_interval As Integer, ByVal inquiryscan_window As Integer) As Long
Declare Function dmWriteScanEnable Lib "TestEngine.dll" (ByVal handle As Long, ByVal scan_enable As Byte) As Long
Declare Function dmSetEventFilterAutoacceptConnection Lib "TestEngine.dll" (ByVal handle As Long) As Long
Declare Function bccmdBc3PsuTrim Lib "TestEngine.dll" (ByVal handle As Long, ByVal data As Integer) As Long
Declare Function bccmdChargerPsuTrim Lib "TestEngine.dll" (ByVal handle As Long, ByVal trim As Integer) As Long
Declare Function bccmdBc3BuckReg Lib "TestEngine.dll" (ByVal handle As Long, ByVal data As Integer) As Long
Declare Function bccmdPsuSmpsEnable Lib "TestEngine.dll" (ByVal handle As Long, ByVal reg As Integer) As Long
Declare Function bccmdBc3MicEn Lib "TestEngine.dll" (ByVal handle As Long, ByVal data As Integer) As Long
Declare Function bccmdPsuHvLinearEnable Lib "TestEngine.dll" (ByVal handle As Long, ByVal reg As Integer) As Long
Declare Function bccmdBc3Led0 Lib "TestEngine.dll" (ByVal handle As Long, ByVal data As Integer) As Long
Declare Function bccmdLedEnable Lib "TestEngine.dll" (ByVal handle As Long, ByVal led As Integer, ByVal state As Integer) As Long
Declare Function bccmdLed0Enable Lib "TestEngine.dll" (ByVal handle As Long, ByVal state As Integer) As Long
Declare Function bccmdBc3Led1 Lib "TestEngine.dll" (ByVal handle As Long, ByVal data As Integer) As Long
Declare Function bccmdLed1Enable Lib "TestEngine.dll" (ByVal handle As Long, ByVal state As Integer) As Long
Declare Function bccmdChargerStatus Lib "TestEngine.dll" (ByVal handle As Long, ByRef state As Integer) As Long
Declare Function bccmdChargerDisable Lib "TestEngine.dll" (ByVal handle As Long, ByVal state As Integer) As Long
Declare Function bccmdChargerSuppressLed0 Lib "TestEngine.dll" (ByVal handle As Long, ByVal state As Integer) As Long
Declare Function hciCreateConnectionNoWait Lib "TestEngine.dll" (ByVal handle As Long, ByVal lap As Long, ByVal uap As Byte, ByVal nap As Integer, ByVal pktType As Integer, ByVal pageScanRepMode As Byte, ByVal pageScanMode As Byte, ByVal clockOffset As Integer, ByVal allowRoleSwitch As Byte) As Long
Declare Function hciWriteAuthenticationEnable Lib "TestEngine.dll" (ByVal handle As Long, ByVal enable As Byte) As Long
Declare Function hciLinkKeyRequestNegativeReply Lib "TestEngine.dll" (ByVal handle As Long, ByVal lap As Long, ByVal uap As Byte, ByVal nap As Integer) As Long
Declare Function hciWaitForConnectionComplete Lib "TestEngine.dll" (ByVal handle As Long, ByRef connHandle As Integer) As Long
Declare Function hciWaitForLinkKeyRequest Lib "TestEngine.dll" (ByVal handle As Long, ByRef lap As Long, ByRef uap As Byte, ByRef nap As Integer) As Long
Declare Function hciWaitForPinCodeRequest Lib "TestEngine.dll" (ByVal handle As Long, ByRef lap As Long, ByRef uap As Byte, ByRef nap As Integer) As Long
Declare Function hciWaitForEncryptionChange Lib "TestEngine.dll" (ByVal handle As Long, ByRef enable As Byte) As Long
Declare Function hciPinCodeRequestReply Lib "TestEngine.dll" (ByVal handle As Long, ByVal lap As Long, ByVal uap As Byte, ByVal nap As Integer, ByVal pinCodeLength As Byte, ByVal pinCode As Byte) As Long
Declare Function hciSetConnectionEncryption Lib "TestEngine.dll" (ByVal handle As Long, ByVal connHandle As Integer, ByVal enable As Byte) As Long
Declare Function vmWrite Lib "TestEngine.dll" (ByVal handle As Long, ByVal data As Integer) As Long
Declare Function vmRead Lib "TestEngine.dll" (ByVal handle As Long, ByVal data As Integer, ByVal timeout As Integer) As Long
Declare Function bccmdSetSingleChan Lib "TestEngine.dll" (ByVal handle As Long, ByVal channel As Integer) As Long
Declare Function bccmdSetHoppingOn Lib "TestEngine.dll" (ByVal handle As Long) As Long
Declare Function bccmdFmSwitchPower Lib "TestEngine.dll" (ByVal handle As Long, ByVal powerOn As Byte) As Long
Declare Function bccmdFmSetFreq Lib "TestEngine.dll" (ByVal handle As Long, ByVal freqKHz As Long) As Long
Declare Function bccmdFmGetRssi Lib "TestEngine.dll" (ByVal handle As Long, ByRef rssi As Byte) As Long
Declare Function bccmdFmGetSnr Lib "TestEngine.dll" (ByVal handle As Long, ByRef snr As Integer) As Long
Declare Function bccmdFmGetIfOffset Lib "TestEngine.dll" (ByVal handle As Long, ByRef offset As Integer) As Long
Declare Function bccmdFmGetStatus Lib "TestEngine.dll" (ByVal handle As Long, ByRef status As Byte) As Long
Declare Function bccmdFmSetupAudio Lib "TestEngine.dll" (ByVal handle As Long, ByVal route As Byte, ByVal gain As Byte, ByVal channel As Byte) As Long
Declare Function bccmdFmVerifyRDSPi Lib "TestEngine.dll" (ByVal handle As Long, ByVal pi As Integer, ByVal timeoutMs As Integer, ByRef matched As Byte) As Long
Declare Function bccmdFmTxSwitchPower Lib "TestEngine.dll" (ByVal handle As Long, ByVal powerOn As Byte) As Long
Declare Function bccmdFmTxSetFreq Lib "TestEngine.dll" (ByVal handle As Long, ByVal freqKHz As Long) As Long
Declare Function bccmdFmTxSetPowerLevel Lib "TestEngine.dll" (ByVal handle As Long, ByVal powerLevel As Integer) As Long
Declare Function bccmdFmTxSetupAudio Lib "TestEngine.dll" (ByVal handle As Long, ByVal route As Byte, ByVal audioGain As Integer) As Long
Declare Function bccmdDisconnectAudio Lib "TestEngine.dll" (ByVal handle As Long) As Long
Declare Function bccmdDirectChargerPsuTrim Lib "TestEngine.dll" (ByVal handle As Long, ByVal trim As Integer) As Long
Declare Function teSupportsHq Lib "TestEngine.dll" (ByVal handle As Long, ByRef hqSupported As Byte) As Long
Declare Function bccmdSetAuxDac Lib "TestEngine.dll" (ByVal handle As Long, ByVal enable As Byte, ByVal level As Byte) As Long
Declare Function bccmdSetMicBiasIf Lib "TestEngine.dll" (ByVal handle As Long, ByVal instance As Byte, ByVal enable As Byte, ByVal voltage As Byte) As Long
Declare Function bccmdSetMicBias Lib "TestEngine.dll" (ByVal handle As Long, ByVal enable As Byte, ByVal voltage As Byte, ByVal current As Byte, ByVal enableLowPowerMode As Byte) As Long
Declare Function teGetAvailableSpiPorts Lib "TestEngine.dll" (ByRef maxLen As Integer, ByVal ports As String, ByVal trans As String, ByRef count As Integer) As Long
Declare Function bccmdProvokeFault Lib "TestEngine.dll" (ByVal handle As Long, ByVal faultCode As Integer) As Long
Declare Function hqGetFaultReports Lib "TestEngine.dll" (ByVal handle As Long, ByVal maxReports As Integer, ByVal codes As Integer, ByVal timestamps As Long, ByVal repeats As Integer, ByRef numReports As Integer, ByVal timeout As Long) As Long
Declare Function teGetFaultDesc Lib "TestEngine.dll" (ByVal handle As Long, ByVal faultCode As Integer, ByVal desc As String) As Long
Declare Function bccmdSetMapScoPcm Lib "TestEngine.dll" (ByVal handle As Long, ByVal enable As Byte) As Long
Declare Function bccmdGetVrefConstant Lib "TestEngine.dll" (ByVal handle As Long, ByRef vref As Integer) As Long
Declare Function bccmdGetVrefAdc Lib "TestEngine.dll" (ByVal handle As Long, ByRef result As Integer, ByRef numBits As Byte) As Long
Declare Function bccmdBC5FMGetI2CState Lib "TestEngine.dll" (ByVal handle As Long, ByRef sda As Byte, ByRef scl As Byte) As Long
Declare Function refEpGetRssiDbm Lib "TestEngine.dll" (ByVal handle As Long, ByVal freqMHz As Integer, ByVal rssiChip As Double, ByRef rssiDbm As Double) As Long
Declare Function refEpGetPaLevel Lib "TestEngine.dll" (ByVal handle As Long, ByVal freqMHz As Integer, ByVal targetPowerDbm As Double, ByRef intPa As Integer, ByRef powerDbm As Double) As Long
Declare Function refEpWriteCalDataFile Lib "TestEngine.dll" (ByVal handle As Long, ByVal filePath As String) As Long
Declare Function refEpLoadCalDataFile Lib "TestEngine.dll" (ByVal handle As Long, ByVal filePath As String) As Long
Declare Function bccmdGetVmStatus Lib "TestEngine.dll" (ByVal handle As Long, ByRef status As Integer, ByRef exitCode As Integer) As Long
Declare Function bccmdI2CTransfer Lib "TestEngine.dll" (ByVal handle As Long, ByVal slaveAddr As Integer, ByVal txOctets As Integer, ByVal rxOctets As Integer, ByVal restart As Byte, ByVal data As Byte, ByRef octets As Integer) As Long
Declare Function radiotestBle Lib "TestEngine.dll" (ByVal handle As Long, ByVal command As Integer, ByVal channel As Byte, ByVal txLength As Byte, ByVal txPayload As Byte) As Long
Declare Function hqGetBleRxPktCount Lib "TestEngine.dll" (ByVal handle As Long, ByVal timeout As Long, ByRef pktCount As Integer) As Long
Declare Function bccmdGetChargerTrims Lib "TestEngine.dll" (ByVal handle As Long, ByRef chgRefTrim As Integer, ByRef hVrefTrim As Integer, ByRef rTrim As Integer, ByRef iTrim As Integer, ByRef iExtTrim As Integer, ByRef iTermTrim As Integer, ByRef vFastTrim As Integer, ByRef hystTrim As Integer) As Long
Declare Function bccmdCapSenseRead Lib "TestEngine.dll" (ByVal handle As Long, ByVal mask As Integer, ByVal values As Integer) As Long
Declare Function bccmdSetSpiLockCustomerKey Lib "TestEngine.dll" (ByVal handle As Long, ByVal custKey As Long) As Long
Declare Function bccmdGetSpiLockStatus Lib "TestEngine.dll" (ByVal handle As Long, ByRef status As Integer) As Long
Declare Function bccmdSpiLockInitiateLock Lib "TestEngine.dll" (ByVal handle As Long) As Long
Declare Function teGetChipDisplayName Lib "TestEngine.dll" (ByVal handle As Long, ByVal maxLen As Long, ByVal name As String) As Long

' DEPRECATED FUNCTIONS

Declare Function bccmdPsuBuckReg Lib "TestEngine.dll" Alias "bccmdPsuSmpsEnable" (ByVal handle As Long, ByVal reg As Integer) As Long
Declare Function bccmdPsuMicEn Lib "TestEngine.dll" Alias "bccmdPsuHvLinearEnable" (ByVal handle As Long, ByVal reg As Integer) As Long
Declare Function bccmdLed0 Lib "TestEngine.dll" Alias "bccmdLed0Enable" (ByVal handle As Long, ByVal state As Integer) As Long
Declare Function bccmdLed1 Lib "TestEngine.dll" Alias "bccmdLed1Enable" (ByVal handle As Long, ByVal state As Integer) As Long
Declare Function bccmdChargerSupressLed0 Lib "TestEngine.dll" Alias "bccmdChargerSuppressLed0" (ByVal handle As Long, ByVal state As Integer) As Long
